/** ------------------------------------------
 *  Autogenerated by ⛋ Terrazzo. DO NOT EDIT!
 * ------------------------------------------- */

export const tokens = {
  "color.systemBlue": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0.47843137254901963,
        1
      ],
      "alpha": 1,
      "hex": "#007aff"
    },
    "light": {
      "colorSpace": "srgb",
      "components": [
        0,
        0.47843137254901963,
        1
      ],
      "alpha": 1,
      "hex": "#007aff"
    },
    "dark": {
      "colorSpace": "srgb",
      "components": [
        0.0392156862745098,
        0.5176470588235295,
        1
      ],
      "alpha": 1,
      "hex": "#0a84ff"
    },
    "light_ax": {
      "colorSpace": "srgb",
      "components": [
        0,
        0.25098039215686274,
        0.8666666666666667
      ],
      "alpha": 1,
      "hex": "#0040dd"
    },
    "dark_ax": {
      "colorSpace": "srgb",
      "components": [
        0.25098039215686274,
        0.611764705882353,
        1
      ],
      "alpha": 1,
      "hex": "#409cff"
    },
  },
  "color.systemBrown": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.6352941176470588,
        0.5176470588235295,
        0.3686274509803922
      ],
      "alpha": 1,
      "hex": "#a2845e"
    },
    "light": {
      "colorSpace": "srgb",
      "components": [
        0.6352941176470588,
        0.5176470588235295,
        0.3686274509803922
      ],
      "alpha": 1,
      "hex": "#a2845e"
    },
    "dark": {
      "colorSpace": "srgb",
      "components": [
        0.6745098039215687,
        0.5568627450980392,
        0.40784313725490196
      ],
      "alpha": 1,
      "hex": "#ac8e68"
    },
    "light_ax": {
      "colorSpace": "srgb",
      "components": [
        0.4980392156862745,
        0.396078431372549,
        0.27058823529411763
      ],
      "alpha": 1,
      "hex": "#7f6545"
    },
    "dark_ax": {
      "colorSpace": "srgb",
      "components": [
        0.7098039215686275,
        0.5803921568627451,
        0.4117647058823529
      ],
      "alpha": 1,
      "hex": "#b59469"
    },
  },
  "color.systemCyan": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.19607843137254902,
        0.6784313725490196,
        0.9019607843137255
      ],
      "alpha": 1,
      "hex": "#32ade6"
    },
    "light": {
      "colorSpace": "srgb",
      "components": [
        0.19607843137254902,
        0.6784313725490196,
        0.9019607843137255
      ],
      "alpha": 1,
      "hex": "#32ade6"
    },
    "dark": {
      "colorSpace": "srgb",
      "components": [
        0.39215686274509803,
        0.8235294117647058,
        1
      ],
      "alpha": 1,
      "hex": "#64d2ff"
    },
    "light_ax": {
      "colorSpace": "srgb",
      "components": [
        0,
        0.44313725490196076,
        0.6431372549019608
      ],
      "alpha": 1,
      "hex": "#0071a4"
    },
    "dark_ax": {
      "colorSpace": "srgb",
      "components": [
        0.4392156862745098,
        0.8431372549019608,
        1
      ],
      "alpha": 1,
      "hex": "#70d7ff"
    },
  },
  "color.systemGray": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.5568627450980392,
        0.5568627450980392,
        0.5764705882352941
      ],
      "alpha": 1,
      "hex": "#8e8e93"
    },
    "light": {
      "colorSpace": "srgb",
      "components": [
        0.5568627450980392,
        0.5568627450980392,
        0.5764705882352941
      ],
      "alpha": 1,
      "hex": "#8e8e93"
    },
    "dark": {
      "colorSpace": "srgb",
      "components": [
        0.5568627450980392,
        0.5568627450980392,
        0.5764705882352941
      ],
      "alpha": 1,
      "hex": "#8e8e93"
    },
    "light_ax": {
      "colorSpace": "srgb",
      "components": [
        0.4235294117647059,
        0.4235294117647059,
        0.4392156862745098
      ],
      "alpha": 1,
      "hex": "#6c6c70"
    },
    "dark_ax": {
      "colorSpace": "srgb",
      "components": [
        0.6823529411764706,
        0.6823529411764706,
        0.6980392156862745
      ],
      "alpha": 1,
      "hex": "#aeaeb2"
    },
  },
  "color.systemGray2": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.6823529411764706,
        0.6823529411764706,
        0.6980392156862745
      ],
      "alpha": 1,
      "hex": "#aeaeb2"
    },
    "light": {
      "colorSpace": "srgb",
      "components": [
        0.6823529411764706,
        0.6823529411764706,
        0.6980392156862745
      ],
      "alpha": 1,
      "hex": "#aeaeb2"
    },
    "dark": {
      "colorSpace": "srgb",
      "components": [
        0.38823529411764707,
        0.38823529411764707,
        0.4
      ],
      "alpha": 1,
      "hex": "#636366"
    },
    "light_ax": {
      "colorSpace": "srgb",
      "components": [
        0.5568627450980392,
        0.5568627450980392,
        0.5764705882352941
      ],
      "alpha": 1,
      "hex": "#8e8e93"
    },
    "dark_ax": {
      "colorSpace": "srgb",
      "components": [
        0.48627450980392156,
        0.48627450980392156,
        0.5019607843137255
      ],
      "alpha": 1,
      "hex": "#7c7c80"
    },
  },
  "color.systemGray3": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.7803921568627451,
        0.7803921568627451,
        0.8
      ],
      "alpha": 1,
      "hex": "#c7c7cc"
    },
    "light": {
      "colorSpace": "srgb",
      "components": [
        0.7803921568627451,
        0.7803921568627451,
        0.8
      ],
      "alpha": 1,
      "hex": "#c7c7cc"
    },
    "dark": {
      "colorSpace": "srgb",
      "components": [
        0.2823529411764706,
        0.2823529411764706,
        0.2901960784313726
      ],
      "alpha": 1,
      "hex": "#48484a"
    },
    "light_ax": {
      "colorSpace": "srgb",
      "components": [
        0.6823529411764706,
        0.6823529411764706,
        0.6980392156862745
      ],
      "alpha": 1,
      "hex": "#aeaeb2"
    },
    "dark_ax": {
      "colorSpace": "srgb",
      "components": [
        0.32941176470588235,
        0.32941176470588235,
        0.33725490196078434
      ],
      "alpha": 1,
      "hex": "#545456"
    },
  },
  "color.systemGray4": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.8196078431372549,
        0.8196078431372549,
        0.8392156862745098
      ],
      "alpha": 1,
      "hex": "#d1d1d6"
    },
    "light": {
      "colorSpace": "srgb",
      "components": [
        0.8196078431372549,
        0.8196078431372549,
        0.8392156862745098
      ],
      "alpha": 1,
      "hex": "#d1d1d6"
    },
    "dark": {
      "colorSpace": "srgb",
      "components": [
        0.22745098039215686,
        0.22745098039215686,
        0.23529411764705882
      ],
      "alpha": 1,
      "hex": "#3a3a3c"
    },
    "light_ax": {
      "colorSpace": "srgb",
      "components": [
        0.7372549019607844,
        0.7372549019607844,
        0.7529411764705882
      ],
      "alpha": 1,
      "hex": "#bcbcc0"
    },
    "dark_ax": {
      "colorSpace": "srgb",
      "components": [
        0.26666666666666666,
        0.26666666666666666,
        0.27450980392156865
      ],
      "alpha": 1,
      "hex": "#444446"
    },
  },
  "color.systemGray5": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.8980392156862745,
        0.8980392156862745,
        0.9176470588235294
      ],
      "alpha": 1,
      "hex": "#e5e5ea"
    },
    "light": {
      "colorSpace": "srgb",
      "components": [
        0.8980392156862745,
        0.8980392156862745,
        0.9176470588235294
      ],
      "alpha": 1,
      "hex": "#e5e5ea"
    },
    "dark": {
      "colorSpace": "srgb",
      "components": [
        0.17254901960784313,
        0.17254901960784313,
        0.1803921568627451
      ],
      "alpha": 1,
      "hex": "#2c2c2e"
    },
    "light_ax": {
      "colorSpace": "srgb",
      "components": [
        0.8470588235294118,
        0.8470588235294118,
        0.8627450980392157
      ],
      "alpha": 1,
      "hex": "#d8d8dc"
    },
    "dark_ax": {
      "colorSpace": "srgb",
      "components": [
        0.21176470588235294,
        0.21176470588235294,
        0.2196078431372549
      ],
      "alpha": 1,
      "hex": "#363638"
    },
  },
  "color.systemGray6": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.9490196078431372,
        0.9490196078431372,
        0.9686274509803922
      ],
      "alpha": 1,
      "hex": "#f2f2f7"
    },
    "light": {
      "colorSpace": "srgb",
      "components": [
        0.9490196078431372,
        0.9490196078431372,
        0.9686274509803922
      ],
      "alpha": 1,
      "hex": "#f2f2f7"
    },
    "dark": {
      "colorSpace": "srgb",
      "components": [
        0.10980392156862745,
        0.10980392156862745,
        0.11764705882352941
      ],
      "alpha": 1,
      "hex": "#1c1c1e"
    },
    "light_ax": {
      "colorSpace": "srgb",
      "components": [
        0.9215686274509803,
        0.9215686274509803,
        0.9411764705882353
      ],
      "alpha": 1,
      "hex": "#ebebf0"
    },
    "dark_ax": {
      "colorSpace": "srgb",
      "components": [
        0.1411764705882353,
        0.1411764705882353,
        0.14901960784313725
      ],
      "alpha": 1,
      "hex": "#242426"
    },
  },
  "color.systemGreen": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.20392156862745098,
        0.7803921568627451,
        0.34901960784313724
      ],
      "alpha": 1,
      "hex": "#34c759"
    },
    "light": {
      "colorSpace": "srgb",
      "components": [
        0.20392156862745098,
        0.7803921568627451,
        0.34901960784313724
      ],
      "alpha": 1,
      "hex": "#34c759"
    },
    "dark": {
      "colorSpace": "srgb",
      "components": [
        0.18823529411764706,
        0.8196078431372549,
        0.34509803921568627
      ],
      "alpha": 1,
      "hex": "#30d158"
    },
    "light_ax": {
      "colorSpace": "srgb",
      "components": [
        0.1411764705882353,
        0.5411764705882353,
        0.23921568627450981
      ],
      "alpha": 1,
      "hex": "#248a3d"
    },
    "dark_ax": {
      "colorSpace": "srgb",
      "components": [
        0.18823529411764706,
        0.8588235294117647,
        0.3568627450980392
      ],
      "alpha": 1,
      "hex": "#30db5b"
    },
  },
  "color.systemIndigo": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.34509803921568627,
        0.33725490196078434,
        0.8392156862745098
      ],
      "alpha": 1,
      "hex": "#5856d6"
    },
    "light": {
      "colorSpace": "srgb",
      "components": [
        0.34509803921568627,
        0.33725490196078434,
        0.8392156862745098
      ],
      "alpha": 1,
      "hex": "#5856d6"
    },
    "dark": {
      "colorSpace": "srgb",
      "components": [
        0.3686274509803922,
        0.3607843137254902,
        0.9019607843137255
      ],
      "alpha": 1,
      "hex": "#5e5ce6"
    },
    "light_ax": {
      "colorSpace": "srgb",
      "components": [
        0.21176470588235294,
        0.20392156862745098,
        0.6392156862745098
      ],
      "alpha": 1,
      "hex": "#3634a3"
    },
    "dark_ax": {
      "colorSpace": "srgb",
      "components": [
        0.49019607843137253,
        0.47843137254901963,
        1
      ],
      "alpha": 1,
      "hex": "#7d7aff"
    },
  },
  "color.systemMint": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0.7803921568627451,
        0.7450980392156863
      ],
      "alpha": 1,
      "hex": "#00c7be"
    },
    "light": {
      "colorSpace": "srgb",
      "components": [
        0,
        0.7803921568627451,
        0.7450980392156863
      ],
      "alpha": 1,
      "hex": "#00c7be"
    },
    "dark": {
      "colorSpace": "srgb",
      "components": [
        0.4,
        0.8313725490196079,
        0.8117647058823529
      ],
      "alpha": 1,
      "hex": "#66d4cf"
    },
    "light_ax": {
      "colorSpace": "srgb",
      "components": [
        0.047058823529411764,
        0.5058823529411764,
        0.4823529411764706
      ],
      "alpha": 1,
      "hex": "#0c817b"
    },
    "dark_ax": {
      "colorSpace": "srgb",
      "components": [
        0.4,
        0.8313725490196079,
        0.8117647058823529
      ],
      "alpha": 1,
      "hex": "#66d4cf"
    },
  },
  "color.systemOrange": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        1,
        0.5843137254901961,
        0
      ],
      "alpha": 1,
      "hex": "#ff9500"
    },
    "light": {
      "colorSpace": "srgb",
      "components": [
        1,
        0.5843137254901961,
        0
      ],
      "alpha": 1,
      "hex": "#ff9500"
    },
    "dark": {
      "colorSpace": "srgb",
      "components": [
        1,
        0.6235294117647059,
        0.0392156862745098
      ],
      "alpha": 1,
      "hex": "#ff9f0a"
    },
    "light_ax": {
      "colorSpace": "srgb",
      "components": [
        0.788235294117647,
        0.20392156862745098,
        0
      ],
      "alpha": 1,
      "hex": "#c93400"
    },
    "dark_ax": {
      "colorSpace": "srgb",
      "components": [
        1,
        0.7019607843137254,
        0.25098039215686274
      ],
      "alpha": 1,
      "hex": "#ffb340"
    },
  },
  "color.systemPurple": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.6862745098039216,
        0.3215686274509804,
        0.8705882352941177
      ],
      "alpha": 1,
      "hex": "#af52de"
    },
    "light": {
      "colorSpace": "srgb",
      "components": [
        0.6862745098039216,
        0.3215686274509804,
        0.8705882352941177
      ],
      "alpha": 1,
      "hex": "#af52de"
    },
    "dark": {
      "colorSpace": "srgb",
      "components": [
        0.7490196078431373,
        0.35294117647058826,
        0.9490196078431372
      ],
      "alpha": 1,
      "hex": "#bf5af2"
    },
    "light_ax": {
      "colorSpace": "srgb",
      "components": [
        0.5372549019607843,
        0.26666666666666666,
        0.6705882352941176
      ],
      "alpha": 1,
      "hex": "#8944ab"
    },
    "dark_ax": {
      "colorSpace": "srgb",
      "components": [
        0.8549019607843137,
        0.5607843137254902,
        1
      ],
      "alpha": 1,
      "hex": "#da8fff"
    },
  },
  "color.systemPink": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        1,
        0.17647058823529413,
        0.3333333333333333
      ],
      "alpha": 1,
      "hex": "#ff2d55"
    },
    "light": {
      "colorSpace": "srgb",
      "components": [
        1,
        0.17647058823529413,
        0.3333333333333333
      ],
      "alpha": 1,
      "hex": "#ff2d55"
    },
    "dark": {
      "colorSpace": "srgb",
      "components": [
        1,
        0.21568627450980393,
        0.37254901960784315
      ],
      "alpha": 1,
      "hex": "#ff375f"
    },
    "light_ax": {
      "colorSpace": "srgb",
      "components": [
        0.8274509803921568,
        0.058823529411764705,
        0.27058823529411763
      ],
      "alpha": 1,
      "hex": "#d30f45"
    },
    "dark_ax": {
      "colorSpace": "srgb",
      "components": [
        1,
        0.39215686274509803,
        0.5098039215686274
      ],
      "alpha": 1,
      "hex": "#ff6482"
    },
  },
  "color.systemRed": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        1,
        0.23137254901960785,
        0.18823529411764706
      ],
      "alpha": 1,
      "hex": "#ff3b30"
    },
    "light": {
      "colorSpace": "srgb",
      "components": [
        1,
        0.23137254901960785,
        0.18823529411764706
      ],
      "alpha": 1,
      "hex": "#ff3b30"
    },
    "dark": {
      "colorSpace": "srgb",
      "components": [
        1,
        0.27058823529411763,
        0.22745098039215686
      ],
      "alpha": 1,
      "hex": "#ff453a"
    },
    "light_ax": {
      "colorSpace": "srgb",
      "components": [
        0.8431372549019608,
        0,
        0.08235294117647059
      ],
      "alpha": 1,
      "hex": "#d70015"
    },
    "dark_ax": {
      "colorSpace": "srgb",
      "components": [
        1,
        0.4117647058823529,
        0.3803921568627451
      ],
      "alpha": 1,
      "hex": "#ff6961"
    },
  },
  "color.systemTeal": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.18823529411764706,
        0.6901960784313725,
        0.7803921568627451
      ],
      "alpha": 1,
      "hex": "#30b0c7"
    },
    "light": {
      "colorSpace": "srgb",
      "components": [
        0.18823529411764706,
        0.6901960784313725,
        0.7803921568627451
      ],
      "alpha": 1,
      "hex": "#30b0c7"
    },
    "dark": {
      "colorSpace": "srgb",
      "components": [
        0.25098039215686274,
        0.7843137254901961,
        0.8784313725490196
      ],
      "alpha": 1,
      "hex": "#40c8e0"
    },
    "light_ax": {
      "colorSpace": "srgb",
      "components": [
        0,
        0.5098039215686274,
        0.6
      ],
      "alpha": 1,
      "hex": "#008299"
    },
    "dark_ax": {
      "colorSpace": "srgb",
      "components": [
        0.36470588235294116,
        0.9019607843137255,
        1
      ],
      "alpha": 1,
      "hex": "#5de6ff"
    },
  },
  "color.systemYellow": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        1,
        0.8,
        0
      ],
      "alpha": 1,
      "hex": "#ffcc00"
    },
    "light": {
      "colorSpace": "srgb",
      "components": [
        1,
        0.8,
        0
      ],
      "alpha": 1,
      "hex": "#ffcc00"
    },
    "dark": {
      "colorSpace": "srgb",
      "components": [
        1,
        0.8392156862745098,
        0.0392156862745098
      ],
      "alpha": 1,
      "hex": "#ffd60a"
    },
    "light_ax": {
      "colorSpace": "srgb",
      "components": [
        0.6980392156862745,
        0.3137254901960784,
        0
      ],
      "alpha": 1,
      "hex": "#b25000"
    },
    "dark_ax": {
      "colorSpace": "srgb",
      "components": [
        1,
        0.8313725490196079,
        0.14901960784313725
      ],
      "alpha": 1,
      "hex": "#ffd426"
    },
  },
  "font.family.sfPro": {
    ".": [
      "SF Pro"
    ],
  },
  "font.family.sfProRounded": {
    ".": [
      "SF Pro Rounded"
    ],
  },
  "font.family.sfCompact": {
    ".": [
      "SF Compact"
    ],
  },
  "font.family.sfMono": {
    ".": [
      "SF Mono"
    ],
  },
  "font.family.newYork": {
    ".": [
      "New York"
    ],
  },
  "font.style.largeTitle": {
    ".": {
      "fontSize": {
        "value": 34,
        "unit": "px"
      },
      "fontWeight": 400,
      "lineHeight": {
        "value": 41,
        "unit": "px"
      }
    },
    "xSmall": {
      "fontSize": {
        "value": 31,
        "unit": "px"
      },
      "lineHeight": {
        "value": 38,
        "unit": "px"
      },
      "fontWeight": 400
    },
    "Small": {
      "fontSize": {
        "value": 32,
        "unit": "px"
      },
      "lineHeight": {
        "value": 39,
        "unit": "px"
      },
      "fontWeight": 400
    },
    "Medium": {
      "fontSize": {
        "value": 33,
        "unit": "px"
      },
      "lineHeight": {
        "value": 40,
        "unit": "px"
      },
      "fontWeight": 400
    },
    "Large": {
      "fontSize": {
        "value": 34,
        "unit": "px"
      },
      "lineHeight": {
        "value": 41,
        "unit": "px"
      },
      "fontWeight": 400
    },
    "xLarge": {
      "fontSize": {
        "value": 36,
        "unit": "px"
      },
      "lineHeight": {
        "value": 43,
        "unit": "px"
      },
      "fontWeight": 400
    },
    "xxLarge": {
      "fontSize": {
        "value": 38,
        "unit": "px"
      },
      "lineHeight": {
        "value": 46,
        "unit": "px"
      },
      "fontWeight": 400
    },
    "xxxLarge": {
      "fontSize": {
        "value": 40,
        "unit": "px"
      },
      "lineHeight": {
        "value": 48,
        "unit": "px"
      },
      "fontWeight": 400
    },
  },
  "font.style.title1": {
    ".": {
      "fontSize": {
        "value": 28,
        "unit": "px"
      },
      "fontWeight": 400,
      "lineHeight": {
        "value": 34,
        "unit": "px"
      }
    },
    "xSmall": {
      "fontSize": {
        "value": 25,
        "unit": "px"
      },
      "lineHeight": {
        "value": 31,
        "unit": "px"
      },
      "fontWeight": 400
    },
    "Small": {
      "fontSize": {
        "value": 26,
        "unit": "px"
      },
      "lineHeight": {
        "value": 32,
        "unit": "px"
      },
      "fontWeight": 400
    },
    "Medium": {
      "fontSize": {
        "value": 27,
        "unit": "px"
      },
      "lineHeight": {
        "value": 33,
        "unit": "px"
      },
      "fontWeight": 400
    },
    "Large": {
      "fontSize": {
        "value": 28,
        "unit": "px"
      },
      "lineHeight": {
        "value": 34,
        "unit": "px"
      },
      "fontWeight": 400
    },
    "xLarge": {
      "fontSize": {
        "value": 30,
        "unit": "px"
      },
      "lineHeight": {
        "value": 37,
        "unit": "px"
      },
      "fontWeight": 400
    },
    "xxLarge": {
      "fontSize": {
        "value": 32,
        "unit": "px"
      },
      "lineHeight": {
        "value": 39,
        "unit": "px"
      },
      "fontWeight": 400
    },
    "xxxLarge": {
      "fontSize": {
        "value": 42,
        "unit": "px"
      },
      "lineHeight": {
        "value": 41,
        "unit": "px"
      },
      "fontWeight": 400
    },
  },
  "font.style.title2": {
    ".": {
      "fontSize": {
        "value": 22,
        "unit": "px"
      },
      "fontWeight": 400,
      "lineHeight": {
        "value": 25,
        "unit": "px"
      }
    },
    "xSmall": {
      "fontSize": {
        "value": 19,
        "unit": "px"
      },
      "lineHeight": {
        "value": 24,
        "unit": "px"
      },
      "fontWeight": 400
    },
    "Small": {
      "fontSize": {
        "value": 20,
        "unit": "px"
      },
      "lineHeight": {
        "value": 25,
        "unit": "px"
      },
      "fontWeight": 400
    },
    "Medium": {
      "fontSize": {
        "value": 21,
        "unit": "px"
      },
      "lineHeight": {
        "value": 26,
        "unit": "px"
      },
      "fontWeight": 400
    },
    "Large": {
      "fontSize": {
        "value": 22,
        "unit": "px"
      },
      "lineHeight": {
        "value": 28,
        "unit": "px"
      },
      "fontWeight": 400
    },
    "xLarge": {
      "fontSize": {
        "value": 24,
        "unit": "px"
      },
      "lineHeight": {
        "value": 30,
        "unit": "px"
      },
      "fontWeight": 400
    },
    "xxLarge": {
      "fontSize": {
        "value": 26,
        "unit": "px"
      },
      "lineHeight": {
        "value": 32,
        "unit": "px"
      },
      "fontWeight": 400
    },
    "xxxLarge": {
      "fontSize": {
        "value": 28,
        "unit": "px"
      },
      "lineHeight": {
        "value": 34,
        "unit": "px"
      },
      "fontWeight": 400
    },
  },
  "font.style.title3": {
    ".": {
      "fontSize": {
        "value": 20,
        "unit": "px"
      },
      "fontWeight": 400,
      "lineHeight": {
        "value": 25,
        "unit": "px"
      }
    },
    "xSmall": {
      "fontSize": {
        "value": 25,
        "unit": "px"
      },
      "lineHeight": {
        "value": 22,
        "unit": "px"
      },
      "fontWeight": 400
    },
    "Small": {
      "fontSize": {
        "value": 26,
        "unit": "px"
      },
      "lineHeight": {
        "value": 23,
        "unit": "px"
      },
      "fontWeight": 400
    },
    "Medium": {
      "fontSize": {
        "value": 27,
        "unit": "px"
      },
      "lineHeight": {
        "value": 24,
        "unit": "px"
      },
      "fontWeight": 400
    },
    "Large": {
      "fontSize": {
        "value": 28,
        "unit": "px"
      },
      "lineHeight": {
        "value": 25,
        "unit": "px"
      },
      "fontWeight": 400
    },
    "xLarge": {
      "fontSize": {
        "value": 30,
        "unit": "px"
      },
      "lineHeight": {
        "value": 28,
        "unit": "px"
      },
      "fontWeight": 400
    },
    "xxLarge": {
      "fontSize": {
        "value": 32,
        "unit": "px"
      },
      "lineHeight": {
        "value": 30,
        "unit": "px"
      },
      "fontWeight": 400
    },
    "xxxLarge": {
      "fontSize": {
        "value": 32,
        "unit": "px"
      },
      "lineHeight": {
        "value": 32,
        "unit": "px"
      },
      "fontWeight": 400
    },
  },
  "font.style.headline": {
    ".": {
      "fontSize": {
        "value": 17,
        "unit": "px"
      },
      "fontWeight": 600,
      "lineHeight": {
        "value": 22,
        "unit": "px"
      }
    },
    "xSmall": {
      "fontSize": {
        "value": 14,
        "unit": "px"
      },
      "lineHeight": {
        "value": 19,
        "unit": "px"
      },
      "fontWeight": 600
    },
    "Small": {
      "fontSize": {
        "value": 15,
        "unit": "px"
      },
      "lineHeight": {
        "value": 20,
        "unit": "px"
      },
      "fontWeight": 600
    },
    "Medium": {
      "fontSize": {
        "value": 16,
        "unit": "px"
      },
      "lineHeight": {
        "value": 21,
        "unit": "px"
      },
      "fontWeight": 600
    },
    "Large": {
      "fontSize": {
        "value": 17,
        "unit": "px"
      },
      "lineHeight": {
        "value": 22,
        "unit": "px"
      },
      "fontWeight": 600
    },
    "xLarge": {
      "fontSize": {
        "value": 19,
        "unit": "px"
      },
      "lineHeight": {
        "value": 24,
        "unit": "px"
      },
      "fontWeight": 600
    },
    "xxLarge": {
      "fontSize": {
        "value": 21,
        "unit": "px"
      },
      "lineHeight": {
        "value": 26,
        "unit": "px"
      },
      "fontWeight": 600
    },
    "xxxLarge": {
      "fontSize": {
        "value": 23,
        "unit": "px"
      },
      "lineHeight": {
        "value": 29,
        "unit": "px"
      },
      "fontWeight": 600
    },
  },
  "font.style.body": {
    ".": {
      "fontSize": {
        "value": 17,
        "unit": "px"
      },
      "fontWeight": 400,
      "lineHeight": {
        "value": 22,
        "unit": "px"
      }
    },
    "xSmall": {
      "fontSize": {
        "value": 14,
        "unit": "px"
      },
      "lineHeight": {
        "value": 19,
        "unit": "px"
      },
      "fontWeight": 400
    },
    "Small": {
      "fontSize": {
        "value": 15,
        "unit": "px"
      },
      "lineHeight": {
        "value": 20,
        "unit": "px"
      },
      "fontWeight": 400
    },
    "Medium": {
      "fontSize": {
        "value": 16,
        "unit": "px"
      },
      "lineHeight": {
        "value": 21,
        "unit": "px"
      },
      "fontWeight": 400
    },
    "Large": {
      "fontSize": {
        "value": 17,
        "unit": "px"
      },
      "lineHeight": {
        "value": 22,
        "unit": "px"
      },
      "fontWeight": 400
    },
    "xLarge": {
      "fontSize": {
        "value": 19,
        "unit": "px"
      },
      "lineHeight": {
        "value": 24,
        "unit": "px"
      },
      "fontWeight": 400
    },
    "xxLarge": {
      "fontSize": {
        "value": 21,
        "unit": "px"
      },
      "lineHeight": {
        "value": 26,
        "unit": "px"
      },
      "fontWeight": 400
    },
    "xxxLarge": {
      "fontSize": {
        "value": 23,
        "unit": "px"
      },
      "lineHeight": {
        "value": 29,
        "unit": "px"
      },
      "fontWeight": 400
    },
  },
  "font.style.callout": {
    ".": {
      "fontSize": {
        "value": 16,
        "unit": "px"
      },
      "fontWeight": 400,
      "lineHeight": {
        "value": 21,
        "unit": "px"
      }
    },
    "xSmall": {
      "fontSize": {
        "value": 13,
        "unit": "px"
      },
      "lineHeight": {
        "value": 18,
        "unit": "px"
      },
      "fontWeight": 400
    },
    "Small": {
      "fontSize": {
        "value": 14,
        "unit": "px"
      },
      "lineHeight": {
        "value": 19,
        "unit": "px"
      },
      "fontWeight": 400
    },
    "Medium": {
      "fontSize": {
        "value": 15,
        "unit": "px"
      },
      "lineHeight": {
        "value": 20,
        "unit": "px"
      },
      "fontWeight": 400
    },
    "Large": {
      "fontSize": {
        "value": 16,
        "unit": "px"
      },
      "lineHeight": {
        "value": 21,
        "unit": "px"
      },
      "fontWeight": 400
    },
    "xLarge": {
      "fontSize": {
        "value": 18,
        "unit": "px"
      },
      "lineHeight": {
        "value": 23,
        "unit": "px"
      },
      "fontWeight": 400
    },
    "xxLarge": {
      "fontSize": {
        "value": 20,
        "unit": "px"
      },
      "lineHeight": {
        "value": 25,
        "unit": "px"
      },
      "fontWeight": 400
    },
    "xxxLarge": {
      "fontSize": {
        "value": 22,
        "unit": "px"
      },
      "lineHeight": {
        "value": 28,
        "unit": "px"
      },
      "fontWeight": 400
    },
  },
  "font.style.subhead": {
    ".": {
      "fontSize": {
        "value": 15,
        "unit": "px"
      },
      "fontWeight": 400,
      "lineHeight": {
        "value": 20,
        "unit": "px"
      }
    },
    "xSmall": {
      "fontSize": {
        "value": 12,
        "unit": "px"
      },
      "lineHeight": {
        "value": 16,
        "unit": "px"
      },
      "fontWeight": 400
    },
    "Small": {
      "fontSize": {
        "value": 13,
        "unit": "px"
      },
      "lineHeight": {
        "value": 18,
        "unit": "px"
      },
      "fontWeight": 400
    },
    "Medium": {
      "fontSize": {
        "value": 14,
        "unit": "px"
      },
      "lineHeight": {
        "value": 19,
        "unit": "px"
      },
      "fontWeight": 400
    },
    "Large": {
      "fontSize": {
        "value": 15,
        "unit": "px"
      },
      "lineHeight": {
        "value": 20,
        "unit": "px"
      },
      "fontWeight": 400
    },
    "xLarge": {
      "fontSize": {
        "value": 17,
        "unit": "px"
      },
      "lineHeight": {
        "value": 22,
        "unit": "px"
      },
      "fontWeight": 400
    },
    "xxLarge": {
      "fontSize": {
        "value": 19,
        "unit": "px"
      },
      "lineHeight": {
        "value": 24,
        "unit": "px"
      },
      "fontWeight": 400
    },
    "xxxLarge": {
      "fontSize": {
        "value": 21,
        "unit": "px"
      },
      "lineHeight": {
        "value": 28,
        "unit": "px"
      },
      "fontWeight": 400
    },
  },
  "font.style.footnote": {
    ".": {
      "fontSize": {
        "value": 13,
        "unit": "px"
      },
      "fontWeight": 400,
      "lineHeight": {
        "value": 18,
        "unit": "px"
      }
    },
    "xSmall": {
      "fontSize": {
        "value": 12,
        "unit": "px"
      },
      "lineHeight": {
        "value": 16,
        "unit": "px"
      },
      "fontWeight": 400
    },
    "Small": {
      "fontSize": {
        "value": 12,
        "unit": "px"
      },
      "lineHeight": {
        "value": 16,
        "unit": "px"
      },
      "fontWeight": 400
    },
    "Medium": {
      "fontSize": {
        "value": 12,
        "unit": "px"
      },
      "lineHeight": {
        "value": 16,
        "unit": "px"
      },
      "fontWeight": 400
    },
    "Large": {
      "fontSize": {
        "value": 13,
        "unit": "px"
      },
      "lineHeight": {
        "value": 18,
        "unit": "px"
      },
      "fontWeight": 400
    },
    "xLarge": {
      "fontSize": {
        "value": 15,
        "unit": "px"
      },
      "lineHeight": {
        "value": 20,
        "unit": "px"
      },
      "fontWeight": 400
    },
    "xxLarge": {
      "fontSize": {
        "value": 17,
        "unit": "px"
      },
      "lineHeight": {
        "value": 22,
        "unit": "px"
      },
      "fontWeight": 400
    },
    "xxxLarge": {
      "fontSize": {
        "value": 19,
        "unit": "px"
      },
      "lineHeight": {
        "value": 24,
        "unit": "px"
      },
      "fontWeight": 400
    },
  },
  "font.style.caption1": {
    ".": {
      "fontSize": {
        "value": 12,
        "unit": "px"
      },
      "fontWeight": 400,
      "lineHeight": {
        "value": 16,
        "unit": "px"
      }
    },
    "xSmall": {
      "fontSize": {
        "value": 11,
        "unit": "px"
      },
      "lineHeight": {
        "value": 13,
        "unit": "px"
      },
      "fontWeight": 400
    },
    "Small": {
      "fontSize": {
        "value": 11,
        "unit": "px"
      },
      "lineHeight": {
        "value": 13,
        "unit": "px"
      },
      "fontWeight": 400
    },
    "Medium": {
      "fontSize": {
        "value": 11,
        "unit": "px"
      },
      "lineHeight": {
        "value": 13,
        "unit": "px"
      },
      "fontWeight": 400
    },
    "Large": {
      "fontSize": {
        "value": 12,
        "unit": "px"
      },
      "lineHeight": {
        "value": 16,
        "unit": "px"
      },
      "fontWeight": 400
    },
    "xLarge": {
      "fontSize": {
        "value": 14,
        "unit": "px"
      },
      "lineHeight": {
        "value": 19,
        "unit": "px"
      },
      "fontWeight": 400
    },
    "xxLarge": {
      "fontSize": {
        "value": 16,
        "unit": "px"
      },
      "lineHeight": {
        "value": 18,
        "unit": "px"
      },
      "fontWeight": 400
    },
    "xxxLarge": {
      "fontSize": {
        "value": 23,
        "unit": "px"
      },
      "lineHeight": {
        "value": 21,
        "unit": "px"
      },
      "fontWeight": 400
    },
  },
  "font.style.caption2": {
    ".": {
      "fontSize": {
        "value": 11,
        "unit": "px"
      },
      "fontWeight": 400,
      "lineHeight": {
        "value": 13,
        "unit": "px"
      }
    },
    "xSmall": {
      "fontSize": {
        "value": 11,
        "unit": "px"
      },
      "lineHeight": {
        "value": 13,
        "unit": "px"
      },
      "fontWeight": 400
    },
    "Small": {
      "fontSize": {
        "value": 11,
        "unit": "px"
      },
      "lineHeight": {
        "value": 13,
        "unit": "px"
      },
      "fontWeight": 400
    },
    "Medium": {
      "fontSize": {
        "value": 11,
        "unit": "px"
      },
      "lineHeight": {
        "value": 13,
        "unit": "px"
      },
      "fontWeight": 400
    },
    "Large": {
      "fontSize": {
        "value": 11,
        "unit": "px"
      },
      "lineHeight": {
        "value": 13,
        "unit": "px"
      },
      "fontWeight": 400
    },
    "xLarge": {
      "fontSize": {
        "value": 13,
        "unit": "px"
      },
      "lineHeight": {
        "value": 18,
        "unit": "px"
      },
      "fontWeight": 400
    },
    "xxLarge": {
      "fontSize": {
        "value": 15,
        "unit": "px"
      },
      "lineHeight": {
        "value": 20,
        "unit": "px"
      },
      "fontWeight": 400
    },
    "xxxLarge": {
      "fontSize": {
        "value": 17,
        "unit": "px"
      },
      "lineHeight": {
        "value": 22,
        "unit": "px"
      },
      "fontWeight": 400
    },
  },
};

/** Get individual token */
export function token(tokenID, modeName = ".") {
  return tokens[tokenID]?.[modeName];
}
