/**
 * Design Tokens
 * Autogenerated from tokens.json.
 * DO NOT EDIT!
 */

export const tokens = {
  'color.blue': '#218bff',
  'color.red': '#fa4549',
};

export const meta = {
  'color.blue': {
    '_original': {
      '$type': 'color',
      '$value': '#218bff',
    },
    '_group': {
      id: 'color',
      '$extensions': {
        requiredModes: [],
      },
    },
    id: 'color.blue',
    '$type': 'color',
    '$value': '#218bff',
  },
  'color.red': {
    '_original': {
      '$type': 'color',
      '$value': '#fa4549',
      '$extensions': {
        mode: {
          light: '#fa4549',
          dark: '#da3633',
        },
      },
    },
    '_group': {
      id: 'color',
      '$extensions': {
        requiredModes: [],
      },
    },
    id: 'color.red',
    '$type': 'color',
    '$value': '#fa4549',
    '$extensions': {
      mode: {
        light: '#fa4549',
        dark: '#da3633',
      },
    },
  },
};

export const modes = {
  'color.red': {
    light: '#fa4549',
    dark: '#da3633',
  },
};

/** Get individual token */
export function token(tokenID, modeName) {
  if (modeName && modes[tokenID] && modeName in modes[tokenID]) return modes[tokenID][modeName];
  return tokens[tokenID];
}
