/**
 * Design Tokens
 * Autogenerated from tokens.json.
 * DO NOT EDIT!
 */

import {
  ColorToken,
  ParsedColorToken,
} from '@cobalt-ui/core';

export declare const tokens: {
  'color.blue': ColorToken['$value'];
  'color.red': ColorToken['$value'];
};

export declare const meta: {
  'color.blue': ParsedColorToken;
  'color.red': ParsedColorToken & { $extensions: { mode: typeof modes['color.red'] } };
};

export declare const modes: {
  'color.red': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
};

export declare function token(tokenID: keyof typeof tokens, modeName?: never): typeof tokens[typeof tokenID];
export declare function token(tokenID: keyof typeof modes, modeName?: keyof typeof modes[typeof tokenID]): typeof modes[typeof tokenID];
