/**
 * Design Tokens
 * Autogenerated from tokens.json.
 * DO NOT EDIT!
 */

import {
  ColorToken,
  ParsedColorToken,
} from '@cobalt-ui/core';

export declare const tokens: {
  color: {
    black: ColorToken['$value'];
    blue: {
      10: ColorToken['$value'];
      20: ColorToken['$value'];
      30: ColorToken['$value'];
      40: ColorToken['$value'];
      50: ColorToken['$value'];
      60: ColorToken['$value'];
      70: ColorToken['$value'];
      80: ColorToken['$value'];
      90: ColorToken['$value'];
      100: ColorToken['$value'];
      '00': ColorToken['$value'];
    };
    white: ColorToken['$value'];
  };
  ui: {
    fg: ColorToken['$value'];
    bg: ColorToken['$value'];
  };
};

export declare const meta: {
  color: {
    black: ParsedColorToken;
    blue: {
      10: ParsedColorToken;
      20: ParsedColorToken;
      30: ParsedColorToken;
      40: ParsedColorToken;
      50: ParsedColorToken;
      60: ParsedColorToken;
      70: ParsedColorToken;
      80: ParsedColorToken;
      90: ParsedColorToken;
      100: ParsedColorToken;
      '00': ParsedColorToken;
    };
    white: ParsedColorToken;
  };
  ui: {
    fg: ParsedColorToken & { $extensions: { mode: typeof modes['ui']['fg'] } };
    bg: ParsedColorToken & { $extensions: { mode: typeof modes['ui']['bg'] } };
  };
};

export declare const modes: {
  ui: {
    fg: {
      light: ColorToken['$value'];
      dark: ColorToken['$value'];
    };
    bg: {
      light: ColorToken['$value'];
      dark: ColorToken['$value'];
    };
  };
};

export declare function token<K extends keyof typeof tokens>(tokenID: K, modeName?: never): typeof tokens[K];
export declare function token<K extends keyof typeof modes, M extends keyof typeof modes[K]>(tokenID: K, modeName: M): typeof modes[K][M];
