packages:
  - packages/**
  - www
  - '!packages/**/test/**'

catalog:
  '@vitejs/plugin-react-swc': ^3.11.0
  react: ^19.1.1
  react-dom: ^19.1.1
  vite: ^7.1.5
  vitest: ^3.2.4

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@swc/core'
  - esbuild
  - sharp

shellEmulator: true
