packages:
  - packages/**
  - www
  - '!packages/**/test/**'

catalog:
  '@humanwhocodes/momoa': ^3.3.10
  '@types/culori': ^4.0.1
  '@types/react': ^19.2.2
  '@types/react-dom': ^19.2.2
  '@vitejs/plugin-react-swc': ^4.2.0
  '@vitest/browser': ^3.2.4
  culori: ^4.0.2
  dtcg-examples: ^0.3.4
  playwright: ^1.55.0
  react: ^19.2.0
  react-dom: ^19.2.0
  vite: ^7.1.9
  vitest: ^4.0.3
  yaml-to-momoa: 0.0.6

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@swc/core'
  - esbuild
  - sharp

shellEmulator: true
