packages:
  - packages/**
  - www
  - '!packages/**/test/**'

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  sharp: true

catalog:
  '@humanwhocodes/momoa': ^3.3.10
  '@types/node': ^25.8.0
  '@types/react': ^19.2.14
  '@types/react-dom': ^19.2.3
  '@vitejs/plugin-react': ^5.2.0
  '@vitest/browser': ^4.1.6
  '@vitest/browser-playwright': ^4.1.6
  '@vitest/coverage-v8': ^4.1.6
  colorjs.io: ^0.6.1
  dtcg-examples: ^1.0.3
  playwright: ^1.60.0
  react: ^19.2.6
  react-dom: ^19.2.6
  vite: ^8.0.13
  vitest: ^4.1.6
  yaml-to-momoa: 0.0.9

onlyBuiltDependencies:
  - '@biomejs/biome'
  - esbuild
  - sharp

shellEmulator: true
