packages:
  - packages/**
  - www
  - '!packages/**/test/**'

catalog:
  '@humanwhocodes/momoa': ^3.3.10
  '@types/culori': ^4.0.1
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  '@vitejs/plugin-react-swc': ^4.2.2
  '@vitest/browser': ^4.0.15
  culori: ^4.0.2
  dtcg-examples: ^0.3.4
  playwright: ^1.55.0
  react: ^19.2.1
  react-dom: ^19.2.1
  vite: ^7.2.6
  vitest: ^4.0.15
  yaml-to-momoa: ^0.0.8

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@swc/core'
  - esbuild
  - sharp

shellEmulator: true
