/** ------------------------------------------
 *  Autogenerated by ⛋ Terrazzo. DO NOT EDIT!
 * ------------------------------------------- */

import type { Resolver, TokenNormalizedSet } from "@terrazzo/parser";

export const PERMUTATIONS: Record<string, TokenNormalizedSet>;

type InputType = {
  "breakpoint": "md" | "lg" | "xlg" | "max";
};;

/** Produce a token set from a given input. */
export const resolver: Pick<Resolver<InputType>, "apply" | "listPermutations">;
