/** ------------------------------------------
 *  Autogenerated by ⛋ Terrazzo. DO NOT EDIT!
 * ------------------------------------------- */

export const tokens = {
  "ease.circ-in": {
    ".": [
      0.55,
      0,
      1,
      0.45
    ],
  },
  "ease.circ-in-out": {
    ".": [
      0.85,
      0,
      0.15,
      1
    ],
  },
  "ease.circ-out": {
    ".": [
      0.33,
      1,
      0.68,
      1
    ],
  },
  "ease.cubic-in": {
    ".": [
      0.32,
      0,
      0.67,
      0
    ],
  },
  "ease.cubic-in-out": {
    ".": [
      0.65,
      0,
      0.35,
      1
    ],
  },
  "ease.cubic-out": {
    ".": [
      0.33,
      1,
      0.68,
      1
    ],
  },
  "ease.linear": {
    ".": [
      0,
      0,
      1,
      1
    ],
  },
  "timing.deliberate": {
    ".": {
      "value": 500,
      "unit": "ms"
    },
  },
  "timing.instant": {
    ".": {
      "value": 50,
      "unit": "ms"
    },
  },
  "timing.moderate": {
    ".": {
      "value": 250,
      "unit": "ms"
    },
  },
  "timing.none": {
    ".": {
      "value": 0,
      "unit": "ms"
    },
  },
  "timing.quick": {
    ".": {
      "value": 100,
      "unit": "ms"
    },
  },
  "timing.slow": {
    ".": {
      "value": 1,
      "unit": "s"
    },
  },
  "transition.circ-in-deliberate": {
    ".": {
      "duration": {
        "value": 500,
        "unit": "ms"
      },
      "timingFunction": [
        0.55,
        0,
        1,
        0.45
      ],
      "delay": {
        "value": 0,
        "unit": "ms"
      }
    },
  },
  "transition.circ-in-instant": {
    ".": {
      "duration": {
        "value": 50,
        "unit": "ms"
      },
      "timingFunction": [
        0.55,
        0,
        1,
        0.45
      ],
      "delay": {
        "value": 0,
        "unit": "ms"
      }
    },
  },
  "transition.circ-in-moderate": {
    ".": {
      "duration": {
        "value": 250,
        "unit": "ms"
      },
      "timingFunction": [
        0.55,
        0,
        1,
        0.45
      ],
      "delay": {
        "value": 0,
        "unit": "ms"
      }
    },
  },
  "transition.circ-in-out-deliberate": {
    ".": {
      "duration": {
        "value": 500,
        "unit": "ms"
      },
      "timingFunction": [
        0.85,
        0,
        0.15,
        1
      ],
      "delay": {
        "value": 0,
        "unit": "ms"
      }
    },
  },
  "transition.circ-in-out-instant": {
    ".": {
      "duration": {
        "value": 50,
        "unit": "ms"
      },
      "timingFunction": [
        0.85,
        0,
        0.15,
        1
      ],
      "delay": {
        "value": 0,
        "unit": "ms"
      }
    },
  },
  "transition.circ-in-out-moderate": {
    ".": {
      "duration": {
        "value": 250,
        "unit": "ms"
      },
      "timingFunction": [
        0.85,
        0,
        0.15,
        1
      ],
      "delay": {
        "value": 0,
        "unit": "ms"
      }
    },
  },
  "transition.circ-in-out-quick": {
    ".": {
      "duration": {
        "value": 100,
        "unit": "ms"
      },
      "timingFunction": [
        0.85,
        0,
        0.15,
        1
      ],
      "delay": {
        "value": 0,
        "unit": "ms"
      }
    },
  },
  "transition.circ-in-out-slow": {
    ".": {
      "duration": {
        "value": 1,
        "unit": "s"
      },
      "timingFunction": [
        0.85,
        0,
        0.15,
        1
      ],
      "delay": {
        "value": 0,
        "unit": "ms"
      }
    },
  },
  "transition.circ-in-quick": {
    ".": {
      "duration": {
        "value": 100,
        "unit": "ms"
      },
      "timingFunction": [
        0.55,
        0,
        1,
        0.45
      ],
      "delay": {
        "value": 0,
        "unit": "ms"
      }
    },
  },
  "transition.circ-in-slow": {
    ".": {
      "duration": {
        "value": 1,
        "unit": "s"
      },
      "timingFunction": [
        0.55,
        0,
        1,
        0.45
      ],
      "delay": {
        "value": 0,
        "unit": "ms"
      }
    },
  },
  "transition.circ-out-deliberate": {
    ".": {
      "duration": {
        "value": 500,
        "unit": "ms"
      },
      "timingFunction": [
        0.33,
        1,
        0.68,
        1
      ],
      "delay": {
        "value": 0,
        "unit": "ms"
      }
    },
  },
  "transition.circ-out-instant": {
    ".": {
      "duration": {
        "value": 50,
        "unit": "ms"
      },
      "timingFunction": [
        0.33,
        1,
        0.68,
        1
      ],
      "delay": {
        "value": 0,
        "unit": "ms"
      }
    },
  },
  "transition.circ-out-moderate": {
    ".": {
      "duration": {
        "value": 250,
        "unit": "ms"
      },
      "timingFunction": [
        0.33,
        1,
        0.68,
        1
      ],
      "delay": {
        "value": 0,
        "unit": "ms"
      }
    },
  },
  "transition.circ-out-quick": {
    ".": {
      "duration": {
        "value": 100,
        "unit": "ms"
      },
      "timingFunction": [
        0.33,
        1,
        0.68,
        1
      ],
      "delay": {
        "value": 0,
        "unit": "ms"
      }
    },
  },
  "transition.circ-out-slow": {
    ".": {
      "duration": {
        "value": 1,
        "unit": "s"
      },
      "timingFunction": [
        0.33,
        1,
        0.68,
        1
      ],
      "delay": {
        "value": 0,
        "unit": "ms"
      }
    },
  },
  "transition.cubic-in-deliberate": {
    ".": {
      "duration": {
        "value": 500,
        "unit": "ms"
      },
      "timingFunction": [
        0.32,
        0,
        0.67,
        0
      ],
      "delay": {
        "value": 0,
        "unit": "ms"
      }
    },
  },
  "transition.cubic-in-instant": {
    ".": {
      "duration": {
        "value": 50,
        "unit": "ms"
      },
      "timingFunction": [
        0.32,
        0,
        0.67,
        0
      ],
      "delay": {
        "value": 0,
        "unit": "ms"
      }
    },
  },
  "transition.cubic-in-moderate": {
    ".": {
      "duration": {
        "value": 250,
        "unit": "ms"
      },
      "timingFunction": [
        0.32,
        0,
        0.67,
        0
      ],
      "delay": {
        "value": 0,
        "unit": "ms"
      }
    },
  },
  "transition.cubic-in-out-deliberate": {
    ".": {
      "duration": {
        "value": 500,
        "unit": "ms"
      },
      "timingFunction": [
        0.65,
        0,
        0.35,
        1
      ],
      "delay": {
        "value": 0,
        "unit": "ms"
      }
    },
  },
  "transition.cubic-in-out-instant": {
    ".": {
      "duration": {
        "value": 50,
        "unit": "ms"
      },
      "timingFunction": [
        0.65,
        0,
        0.35,
        1
      ],
      "delay": {
        "value": 0,
        "unit": "ms"
      }
    },
  },
  "transition.cubic-in-out-moderate": {
    ".": {
      "duration": {
        "value": 250,
        "unit": "ms"
      },
      "timingFunction": [
        0.65,
        0,
        0.35,
        1
      ],
      "delay": {
        "value": 0,
        "unit": "ms"
      }
    },
  },
  "transition.cubic-in-out-quick": {
    ".": {
      "duration": {
        "value": 100,
        "unit": "ms"
      },
      "timingFunction": [
        0.65,
        0,
        0.35,
        1
      ],
      "delay": {
        "value": 0,
        "unit": "ms"
      }
    },
  },
  "transition.cubic-in-out-slow": {
    ".": {
      "duration": {
        "value": 1,
        "unit": "s"
      },
      "timingFunction": [
        0.65,
        0,
        0.35,
        1
      ],
      "delay": {
        "value": 0,
        "unit": "ms"
      }
    },
  },
  "transition.cubic-in-quick": {
    ".": {
      "duration": {
        "value": 100,
        "unit": "ms"
      },
      "timingFunction": [
        0.32,
        0,
        0.67,
        0
      ],
      "delay": {
        "value": 0,
        "unit": "ms"
      }
    },
  },
  "transition.cubic-in-slow": {
    ".": {
      "duration": {
        "value": 1,
        "unit": "s"
      },
      "timingFunction": [
        0.32,
        0,
        0.67,
        0
      ],
      "delay": {
        "value": 0,
        "unit": "ms"
      }
    },
  },
  "transition.cubic-out-deliberate": {
    ".": {
      "duration": {
        "value": 500,
        "unit": "ms"
      },
      "timingFunction": [
        0.33,
        1,
        0.68,
        1
      ],
      "delay": {
        "value": 0,
        "unit": "ms"
      }
    },
  },
  "transition.cubic-out-instant": {
    ".": {
      "duration": {
        "value": 50,
        "unit": "ms"
      },
      "timingFunction": [
        0.33,
        1,
        0.68,
        1
      ],
      "delay": {
        "value": 0,
        "unit": "ms"
      }
    },
  },
  "transition.cubic-out-moderate": {
    ".": {
      "duration": {
        "value": 250,
        "unit": "ms"
      },
      "timingFunction": [
        0.33,
        1,
        0.68,
        1
      ],
      "delay": {
        "value": 0,
        "unit": "ms"
      }
    },
  },
  "transition.cubic-out-quick": {
    ".": {
      "duration": {
        "value": 100,
        "unit": "ms"
      },
      "timingFunction": [
        0.33,
        1,
        0.68,
        1
      ],
      "delay": {
        "value": 0,
        "unit": "ms"
      }
    },
  },
  "transition.cubic-out-slow": {
    ".": {
      "duration": {
        "value": 1,
        "unit": "s"
      },
      "timingFunction": [
        0.33,
        1,
        0.68,
        1
      ],
      "delay": {
        "value": 0,
        "unit": "ms"
      }
    },
  },
  "transition.linear-deliberate": {
    ".": {
      "duration": {
        "value": 500,
        "unit": "ms"
      },
      "timingFunction": [
        0,
        0,
        1,
        1
      ],
      "delay": {
        "value": 0,
        "unit": "ms"
      }
    },
  },
  "transition.linear-instant": {
    ".": {
      "duration": {
        "value": 50,
        "unit": "ms"
      },
      "timingFunction": [
        0,
        0,
        1,
        1
      ],
      "delay": {
        "value": 0,
        "unit": "ms"
      }
    },
  },
  "transition.linear-moderate": {
    ".": {
      "duration": {
        "value": 250,
        "unit": "ms"
      },
      "timingFunction": [
        0,
        0,
        1,
        1
      ],
      "delay": {
        "value": 0,
        "unit": "ms"
      }
    },
  },
  "transition.linear-quick": {
    ".": {
      "duration": {
        "value": 100,
        "unit": "ms"
      },
      "timingFunction": [
        0,
        0,
        1,
        1
      ],
      "delay": {
        "value": 0,
        "unit": "ms"
      }
    },
  },
  "transition.linear-slow": {
    ".": {
      "duration": {
        "value": 1,
        "unit": "s"
      },
      "timingFunction": [
        0,
        0,
        1,
        1
      ],
      "delay": {
        "value": 0,
        "unit": "ms"
      }
    },
  },
};

/** Get individual token */
export function token(tokenID, modeName = ".") {
  return tokens[tokenID]?.[modeName];
}
