/** ------------------------------------------
 *  Autogenerated by ⛋ Terrazzo. DO NOT EDIT!
 * ------------------------------------------- */

export const tokens = {
  "border.solid": {
    ".": {
      "color": {
        "colorSpace": "srgb",
        "channels": [
          0.65,
          0.69,
          0.71
        ],
        "alpha": 1
      },
      "style": "solid",
      "width": {
        "value": 1,
        "unit": "px"
      }
    },
    "light": {
      "color": {
        "colorSpace": "srgb",
        "channels": [
          0.65,
          0.69,
          0.71
        ],
        "alpha": 1
      },
      "style": "solid",
      "width": {
        "value": 1,
        "unit": "px"
      }
    },
    "dark": {
      "color": {
        "colorSpace": "srgb",
        "channels": [
          0.08,
          0.09,
          0.11
        ],
        "alpha": 1
      },
      "style": "solid",
      "width": {
        "value": 1,
        "unit": "px"
      }
    },
  },
  "border.dashed": {
    ".": {
      "color": {
        "colorSpace": "srgb",
        "channels": [
          0.65,
          0.69,
          0.71
        ],
        "alpha": 1
      },
      "style": {
        "dashArray": [
          "0.5rem",
          "0.25rem"
        ],
        "lineCap": "round"
      },
      "width": {
        "value": 1.5,
        "unit": "px"
      }
    },
    "light": {
      "color": {
        "colorSpace": "srgb",
        "channels": [
          0.65,
          0.69,
          0.71
        ],
        "alpha": 1
      },
      "style": {
        "dashArray": [
          "0.5rem",
          "0.25rem"
        ],
        "lineCap": "round"
      },
      "width": {
        "value": 1.5,
        "unit": "px"
      }
    },
    "dark": {
      "color": {
        "colorSpace": "srgb",
        "channels": [
          0.08,
          0.09,
          0.11
        ],
        "alpha": 1
      },
      "style": {
        "dashArray": [
          "0.5rem",
          "0.25rem"
        ],
        "lineCap": "round"
      },
      "width": {
        "value": 1.5,
        "unit": "px"
      }
    },
  },
  "border.default": {
    ".": {
      "color": {
        "colorSpace": "oklch",
        "channels": [
          0.2,
          0.001422,
          310
        ],
        "alpha": 1
      },
      "style": "solid",
      "width": {
        "value": 2.5,
        "unit": "px"
      }
    },
  },
  "color.base.gray.10": {
    ".": {
      "colorSpace": "oklch",
      "channels": [
        0.1,
        0.002,
        270
      ],
      "alpha": 1
    },
  },
  "color.base.gray.15": {
    ".": {
      "colorSpace": "oklch",
      "channels": [
        0.15,
        0.001577,
        290
      ],
      "alpha": 1
    },
  },
  "color.base.gray.20": {
    ".": {
      "colorSpace": "oklch",
      "channels": [
        0.2,
        0.001422,
        310
      ],
      "alpha": 1
    },
  },
  "color.base.gray.25": {
    ".": {
      "colorSpace": "oklch",
      "channels": [
        0.25,
        0.001614,
        340
      ],
      "alpha": 1
    },
  },
  "color.base.gray.30": {
    ".": {
      "colorSpace": "oklch",
      "channels": [
        0.3,
        0.002057,
        0
      ],
      "alpha": 1
    },
  },
  "color.base.gray.40": {
    ".": {
      "colorSpace": "oklch",
      "channels": [
        0.4,
        0.003261,
        18
      ],
      "alpha": 1
    },
  },
  "color.base.gray.50": {
    ".": {
      "colorSpace": "oklch",
      "channels": [
        0.5,
        0.004607,
        27
      ],
      "alpha": 1
    },
  },
  "color.base.gray.60": {
    ".": {
      "colorSpace": "oklch",
      "channels": [
        0.6,
        0.006,
        31
      ],
      "alpha": 1
    },
  },
  "color.base.gray.70": {
    ".": {
      "colorSpace": "oklch",
      "channels": [
        0.7,
        0.00575,
        31
      ],
      "alpha": 1
    },
  },
  "color.base.gray.80": {
    ".": {
      "colorSpace": "oklch",
      "channels": [
        0.8,
        0.0055,
        31
      ],
      "alpha": 1
    },
  },
  "color.base.gray.85": {
    ".": {
      "colorSpace": "oklch",
      "channels": [
        0.85,
        0.005375,
        31
      ],
      "alpha": 1
    },
  },
  "color.base.gray.90": {
    ".": {
      "colorSpace": "oklch",
      "channels": [
        0.9,
        0.00525,
        31
      ],
      "alpha": 1
    },
  },
  "color.base.gray.95": {
    ".": {
      "colorSpace": "oklch",
      "channels": [
        0.94,
        0.005125,
        31
      ],
      "alpha": 1
    },
  },
  "color.base.gray.100": {
    ".": {
      "colorSpace": "oklch",
      "channels": [
        1,
        0,
        0
      ],
      "alpha": 1
    },
  },
  "color.border": {
    ".": {
      "colorSpace": "oklch",
      "channels": [
        0.2,
        0.001422,
        310
      ],
      "alpha": 1
    },
    "light": {
      "colorSpace": "oklch",
      "channels": [
        0.2,
        0.001422,
        310
      ],
      "alpha": 1
    },
    "dark": {
      "colorSpace": "oklch",
      "channels": [
        0.8,
        0.0055,
        31
      ],
      "alpha": 1
    },
  },
};

/** Get individual token */
export function token(tokenID, modeName = ".") {
  return tokens[tokenID]?.[modeName];
}
