/** ------------------------------------------
 *  Autogenerated by ⛋ Terrazzo. DO NOT EDIT!
 * ------------------------------------------- */

import type {
  BorderTokenNormalized,
} from "@terrazzo/parser";

export declare const tokens: {
  /** Default border */
  "border.solid": Record<"." | "light" | "dark", BorderTokenNormalized["$value"]>;
  /** Border for placeholder items */
  "border.dashed": Record<"." | "light" | "dark", BorderTokenNormalized["$value"]>;
};

export declare function token<K extends keyof typeof tokens>(tokenID: K, modeName?: never): (typeof tokens)[K]["."];
export declare function token<K extends keyof typeof tokens, M extends keyof (typeof tokens)[K]>(tokenID: K, modeName: M): (typeof tokens)[K][M];
