/**
 * Design Tokens
 * Autogenerated from tokens.json.
 * DO NOT EDIT!
 */

import {
  BorderToken,
  ParsedBorderToken,
} from '@cobalt-ui/core';

export declare const tokens: {
  border: BorderToken['$value'];
};

export declare const meta: {
  border: ParsedBorderToken & { $extensions: { mode: typeof modes['border'] } };
};

export declare const modes: {
  border: {
    light: BorderToken['$value'];
    dark: BorderToken['$value'];
  };
};

export declare function token<K extends keyof typeof tokens>(tokenID: K, modeName?: never): typeof tokens[K];
export declare function token<K extends keyof typeof modes, M extends keyof typeof modes[K]>(tokenID: K, modeName: M): typeof modes[K][M];
