/**
 * Design Tokens
 * Autogenerated from tokens.json.
 * DO NOT EDIT!
 */

import {
  BorderToken,
  ParsedBorderToken,
} from '@cobalt-ui/core';

export declare const tokens: {
  border: BorderToken['$value'];
};

export declare const meta: {
  border: ParsedBorderToken & { $extensions: { mode: typeof modes['border'] } };
};

export declare const modes: {
  border: {
    light: BorderToken['$value'];
    dark: BorderToken['$value'];
  };
};

export declare function token(tokenID: keyof typeof tokens, modeName?: undefined): typeof tokens[typeof tokenID];
export declare function token(tokenID: keyof typeof modes, modeName?: keyof typeof modes[typeof tokenID]): typeof modes[typeof tokenID];
