/** ------------------------------------------
 *  Autogenerated by ⛋ Terrazzo. DO NOT EDIT!
 * ------------------------------------------- */

export const tokens = {
  "color.black": {
    ".": {
      "colorSpace": "oklch",
      "channels": [
        0.08,
        0.002,
        247.86
      ],
      "alpha": 1
    },
  },
  "color.blue.1": {
    ".": {
      "colorSpace": "oklch",
      "channels": [
        0.9931,
        0.003,
        247.86
      ],
      "alpha": 1
    },
  },
  "color.blue.2": {
    ".": {
      "colorSpace": "oklch",
      "channels": [
        0.982,
        0.009,
        242.83
      ],
      "alpha": 1
    },
  },
  "color.blue.3": {
    ".": {
      "colorSpace": "oklch",
      "channels": [
        0.9597,
        0.02,
        238.66
      ],
      "alpha": 1
    },
  },
  "color.blue.4": {
    ".": {
      "colorSpace": "oklch",
      "channels": [
        0.9381,
        0.035,
        234.8
      ],
      "alpha": 1
    },
  },
  "color.blue.5": {
    ".": {
      "colorSpace": "oklch",
      "channels": [
        0.9051,
        0.051,
        240.31
      ],
      "alpha": 1
    },
  },
  "color.blue.6": {
    ".": {
      "colorSpace": "oklch",
      "channels": [
        0.8633,
        0.068,
        243.3
      ],
      "alpha": 1
    },
  },
  "color.blue.7": {
    ".": {
      "colorSpace": "oklch",
      "channels": [
        0.8098,
        0.089,
        243.05
      ],
      "alpha": 1
    },
  },
  "color.blue.8": {
    ".": {
      "colorSpace": "oklch",
      "channels": [
        0.7336,
        0.121,
        243.09
      ],
      "alpha": 1
    },
  },
  "color.blue.9": {
    ".": {
      "colorSpace": "oklch",
      "channels": [
        0.6493,
        0.193,
        251.78
      ],
      "alpha": 1
    },
  },
  "color.blue.10": {
    ".": {
      "colorSpace": "oklch",
      "channels": [
        0.6223,
        0.183,
        251.7
      ],
      "alpha": 1
    },
  },
  "color.blue.11": {
    ".": {
      "colorSpace": "oklch",
      "channels": [
        0.5558,
        0.162,
        252.19
      ],
      "alpha": 1
    },
  },
  "color.blue.12": {
    ".": {
      "colorSpace": "oklch",
      "channels": [
        0.324,
        0.096,
        258.82
      ],
      "alpha": 1
    },
  },
  "color.white": {
    ".": {
      "colorSpace": "oklch",
      "channels": [
        1,
        0,
        0
      ],
      "alpha": 1
    },
  },
  "ui.bg": {
    ".": {
      "colorSpace": "oklch",
      "channels": [
        1,
        0,
        0
      ],
      "alpha": 1
    },
    "light": {
      "colorSpace": "oklch",
      "channels": [
        1,
        0,
        0
      ],
      "alpha": 1
    },
    "dark": {
      "colorSpace": "oklch",
      "channels": [
        0.08,
        0.002,
        247.86
      ],
      "alpha": 1
    },
  },
  "ui.fg": {
    ".": {
      "colorSpace": "oklch",
      "channels": [
        0.08,
        0.002,
        247.86
      ],
      "alpha": 1
    },
    "light": {
      "colorSpace": "oklch",
      "channels": [
        0.08,
        0.002,
        247.86
      ],
      "alpha": 1
    },
    "dark": {
      "colorSpace": "oklch",
      "channels": [
        1,
        0,
        0
      ],
      "alpha": 1
    },
  },
};

/** Get individual token */
export function token(tokenID, modeName = ".") {
  return tokens[tokenID]?.[modeName];
}
