/**
 * Design Tokens
 * Autogenerated from tokens.json.
 * DO NOT EDIT!
 */

export const tokens = {
  'color.black': '#00193f',
  'color.blue.10': '#062053',
  'color.blue.20': '#0f2868',
  'color.blue.30': '#192f7d',
  'color.blue.40': '#223793',
  /** Medium blue */
  'color.blue.50': '#2b3faa',
  'color.blue.60': '#3764ba',
  'color.blue.70': '#4887c9',
  'color.blue.80': '#5ca9d7',
  'color.blue.90': '#72cce5',
  'color.blue.100': '#89eff1',
  'color.blue.00': '#00193f',
  'color.white': '#ffffff',
  'ui.fg': '#00193f',
  'ui.bg': '#ffffff',
};

export const meta = {
  'color.black': {
    '_original': {
      '$value': '#00193f',
    },
    '_group': {
      id: 'color',
      '$extensions': {
        requiredModes: [],
      },
      '$type': 'color',
      '$description': 'Brand blue',
    },
    '$type': 'color',
    '$value': '#00193f',
  },
  'color.blue.10': {
    '_original': {
      '$value': '#062053',
    },
    '_group': {
      id: 'color.blue',
      '$extensions': {
        requiredModes: [],
      },
      '$type': 'color',
      '$description': 'Brand blue',
    },
    '$type': 'color',
    '$value': '#062053',
  },
  'color.blue.20': {
    '_original': {
      '$value': '#0f2868',
    },
    '_group': {
      id: 'color.blue',
      '$extensions': {
        requiredModes: [],
      },
      '$type': 'color',
      '$description': 'Brand blue',
    },
    '$type': 'color',
    '$value': '#0f2868',
  },
  'color.blue.30': {
    '_original': {
      '$value': '#192f7d',
    },
    '_group': {
      id: 'color.blue',
      '$extensions': {
        requiredModes: [],
      },
      '$type': 'color',
      '$description': 'Brand blue',
    },
    '$type': 'color',
    '$value': '#192f7d',
  },
  'color.blue.40': {
    '_original': {
      '$value': '#223793',
    },
    '_group': {
      id: 'color.blue',
      '$extensions': {
        requiredModes: [],
      },
      '$type': 'color',
      '$description': 'Brand blue',
    },
    '$type': 'color',
    '$value': '#223793',
  },
  'color.blue.50': {
    '_original': {
      '$description': 'Medium blue',
      '$value': '#2b3faa',
    },
    '_group': {
      id: 'color.blue',
      '$extensions': {
        requiredModes: [],
      },
      '$type': 'color',
      '$description': 'Brand blue',
    },
    '$type': 'color',
    '$description': 'Medium blue',
    '$value': '#2b3faa',
  },
  'color.blue.60': {
    '_original': {
      '$value': '#3764ba',
    },
    '_group': {
      id: 'color.blue',
      '$extensions': {
        requiredModes: [],
      },
      '$type': 'color',
      '$description': 'Brand blue',
    },
    '$type': 'color',
    '$value': '#3764ba',
  },
  'color.blue.70': {
    '_original': {
      '$value': '#4887c9',
    },
    '_group': {
      id: 'color.blue',
      '$extensions': {
        requiredModes: [],
      },
      '$type': 'color',
      '$description': 'Brand blue',
    },
    '$type': 'color',
    '$value': '#4887c9',
  },
  'color.blue.80': {
    '_original': {
      '$value': '#5ca9d7',
    },
    '_group': {
      id: 'color.blue',
      '$extensions': {
        requiredModes: [],
      },
      '$type': 'color',
      '$description': 'Brand blue',
    },
    '$type': 'color',
    '$value': '#5ca9d7',
  },
  'color.blue.90': {
    '_original': {
      '$value': '#72cce5',
    },
    '_group': {
      id: 'color.blue',
      '$extensions': {
        requiredModes: [],
      },
      '$type': 'color',
      '$description': 'Brand blue',
    },
    '$type': 'color',
    '$value': '#72cce5',
  },
  'color.blue.100': {
    '_original': {
      '$value': '#89eff1',
    },
    '_group': {
      id: 'color.blue',
      '$extensions': {
        requiredModes: [],
      },
      '$type': 'color',
      '$description': 'Brand blue',
    },
    '$type': 'color',
    '$value': '#89eff1',
  },
  'color.blue.00': {
    '_original': {
      '$value': '{color.black}',
    },
    '_group': {
      id: 'color.blue',
      '$extensions': {
        requiredModes: [],
      },
      '$type': 'color',
      '$description': 'Brand blue',
    },
    '$type': 'color',
    '$value': '{color.black}',
  },
  'color.white': {
    '_original': {
      '$value': '#ffffff',
    },
    '_group': {
      id: 'color',
      '$extensions': {
        requiredModes: [],
      },
      '$type': 'color',
      '$description': 'Brand blue',
    },
    '$type': 'color',
    '$value': '#ffffff',
  },
  'ui.fg': {
    '_original': {
      '$type': 'color',
      '$value': '{color.black}',
      '$extensions': {
        mode: {
          light: '{color.black}',
          dark: '{color.white}',
        },
      },
    },
    '_group': {
      id: 'ui',
      '$extensions': {
        requiredModes: [],
      },
    },
    '$type': 'color',
    '$value': '{color.black}',
    '$extensions': {
      mode: {
        light: '{color.black}',
        dark: '{color.white}',
      },
    },
  },
  'ui.bg': {
    '_original': {
      '$type': 'color',
      '$value': '{color.white}',
      '$extensions': {
        mode: {
          light: '{color.white}',
          dark: '{color.black}',
        },
      },
    },
    '_group': {
      id: 'ui',
      '$extensions': {
        requiredModes: [],
      },
    },
    '$type': 'color',
    '$value': '{color.white}',
    '$extensions': {
      mode: {
        light: '{color.white}',
        dark: '{color.black}',
      },
    },
  },
};

export const modes = {
  'ui.fg': {
    light: '#00193f',
    dark: '#ffffff',
  },
  'ui.bg': {
    light: '#ffffff',
    dark: '#00193f',
  },
};

/** Get individual token */
export function token(tokenID, modeName) {
  if (modeName && modes[tokenID] && modeName in modes[tokenID]) return modes[tokenID][modeName];
  return tokens[tokenID];
}
