/**
 * Design Tokens
 * Autogenerated from tokens.json.
 * DO NOT EDIT!
 */

export const tokens = {
  'typography.body': {
    fontFamily: ['Helvetica'],
    fontSize: '17px',
    fontWeight: 400,
    lineHeight: '22px',
  },
  'typography.family.body': ['IBM Plex Sans', '-system-ui', 'sans-serif'],
  'typography.family.heading': ['Helvetica'],
  'typography.largeTitle': {
    fontFamily: ['Helvetica'],
    fontSize: '34px',
    fontWeight: 400,
    lineHeight: '41px',
  },
};

export const meta = {
  'typography.body': {
    _original: {
      $type: 'typography',
      $value: {
        fontFamily: '{typography.family.heading}',
        fontSize: '17px',
        fontWeight: 400,
        lineHeight: '22px',
      },
      $extensions: {
        mode: {
          xs: {
            fontSize: '14px',
            lineHeight: '19px',
          },
          s: {
            fontSize: '15px',
            lineHeight: '20px',
          },
          m: {
            fontSize: '16px',
            lineHeight: '21px',
          },
          l: {
            fontSize: '17px',
            lineHeight: '22px',
          },
          xl: {
            fontSize: '19px',
            lineHeight: '24px',
          },
          '2xl': {
            fontSize: '21px',
            lineHeight: '26px',
          },
          '3xl': {
            fontSize: '23px',
            lineHeight: '29px',
          },
        },
      },
    },
    _group: {
      id: 'typography',
      $extensions: {
        requiredModes: [],
      },
    },
    id: 'typography.body',
    $type: 'typography',
    $value: {
      fontFamily: ['Helvetica'],
      fontSize: '17px',
      fontWeight: 400,
      lineHeight: '22px',
    },
    $extensions: {
      mode: {
        xs: {
          fontSize: '14px',
          lineHeight: '19px',
        },
        s: {
          fontSize: '15px',
          lineHeight: '20px',
        },
        m: {
          fontSize: '16px',
          lineHeight: '21px',
        },
        l: {
          fontSize: '17px',
          lineHeight: '22px',
        },
        xl: {
          fontSize: '19px',
          lineHeight: '24px',
        },
        '2xl': {
          fontSize: '21px',
          lineHeight: '26px',
        },
        '3xl': {
          fontSize: '23px',
          lineHeight: '29px',
        },
      },
    },
  },
  'typography.family.body': {
    _original: {
      $type: 'fontFamily',
      $value: ['IBM Plex Sans', '-system-ui', 'sans-serif'],
    },
    _group: {
      id: 'typography.family',
      $extensions: {
        requiredModes: [],
      },
    },
    id: 'typography.family.body',
    $type: 'fontFamily',
    $value: ['IBM Plex Sans', '-system-ui', 'sans-serif'],
  },
  'typography.family.heading': {
    _original: {
      $type: 'fontFamily',
      $value: 'Helvetica',
    },
    _group: {
      id: 'typography.family',
      $extensions: {
        requiredModes: [],
      },
    },
    id: 'typography.family.heading',
    $type: 'fontFamily',
    $value: ['Helvetica'],
  },
  'typography.largeTitle': {
    _original: {
      $type: 'typography',
      $value: {
        fontFamily: '{typography.family.heading}',
        fontSize: '34px',
        fontWeight: 400,
        lineHeight: '41px',
      },
      $extensions: {
        mode: {
          xs: {
            fontSize: '31px',
            lineHeight: '38px',
          },
          s: {
            fontSize: '32px',
            lineHeight: '39px',
          },
          m: {
            fontSize: '33px',
            lineHeight: '40px',
          },
          l: {
            fontSize: '34px',
            lineHeight: '41px',
          },
          xl: {
            fontSize: '36px',
            lineHeight: '43px',
          },
          '2xl': {
            fontSize: '38px',
            lineHeight: '46px',
          },
          '3xl': {
            fontSize: '40px',
            lineHeight: '48px',
          },
        },
      },
    },
    _group: {
      id: 'typography',
      $extensions: {
        requiredModes: [],
      },
    },
    id: 'typography.largeTitle',
    $type: 'typography',
    $value: {
      fontFamily: ['Helvetica'],
      fontSize: '34px',
      fontWeight: 400,
      lineHeight: '41px',
    },
    $extensions: {
      mode: {
        xs: {
          fontSize: '31px',
          lineHeight: '38px',
        },
        s: {
          fontSize: '32px',
          lineHeight: '39px',
        },
        m: {
          fontSize: '33px',
          lineHeight: '40px',
        },
        l: {
          fontSize: '34px',
          lineHeight: '41px',
        },
        xl: {
          fontSize: '36px',
          lineHeight: '43px',
        },
        '2xl': {
          fontSize: '38px',
          lineHeight: '46px',
        },
        '3xl': {
          fontSize: '40px',
          lineHeight: '48px',
        },
      },
    },
  },
};

export const modes = {
  'typography.body': {
    xs: {
      fontFamily: ['Helvetica'],
      fontSize: '14px',
      fontWeight: 400,
      lineHeight: '19px',
    },
    s: {
      fontFamily: ['Helvetica'],
      fontSize: '15px',
      fontWeight: 400,
      lineHeight: '20px',
    },
    m: {
      fontFamily: ['Helvetica'],
      fontSize: '16px',
      fontWeight: 400,
      lineHeight: '21px',
    },
    l: {
      fontFamily: ['Helvetica'],
      fontSize: '17px',
      fontWeight: 400,
      lineHeight: '22px',
    },
    xl: {
      fontFamily: ['Helvetica'],
      fontSize: '19px',
      fontWeight: 400,
      lineHeight: '24px',
    },
    '2xl': {
      fontFamily: ['Helvetica'],
      fontSize: '21px',
      fontWeight: 400,
      lineHeight: '26px',
    },
    '3xl': {
      fontFamily: ['Helvetica'],
      fontSize: '23px',
      fontWeight: 400,
      lineHeight: '29px',
    },
  },
  'typography.largeTitle': {
    xs: {
      fontFamily: ['Helvetica'],
      fontSize: '31px',
      fontWeight: 400,
      lineHeight: '38px',
    },
    s: {
      fontFamily: ['Helvetica'],
      fontSize: '32px',
      fontWeight: 400,
      lineHeight: '39px',
    },
    m: {
      fontFamily: ['Helvetica'],
      fontSize: '33px',
      fontWeight: 400,
      lineHeight: '40px',
    },
    l: {
      fontFamily: ['Helvetica'],
      fontSize: '34px',
      fontWeight: 400,
      lineHeight: '41px',
    },
    xl: {
      fontFamily: ['Helvetica'],
      fontSize: '36px',
      fontWeight: 400,
      lineHeight: '43px',
    },
    '2xl': {
      fontFamily: ['Helvetica'],
      fontSize: '38px',
      fontWeight: 400,
      lineHeight: '46px',
    },
    '3xl': {
      fontFamily: ['Helvetica'],
      fontSize: '40px',
      fontWeight: 400,
      lineHeight: '48px',
    },
  },
};

/** Get individual token */
export function token(tokenID, modeName) {
  if (modeName && modes[tokenID] && modeName in modes[tokenID]) return modes[tokenID][modeName];
  return tokens[tokenID];
}
