import fsSync from 'node:fs';
import fs from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { execaNode } from 'execa';
import { describe, expect, it } from 'vitest';

const cmd = '../../../../cli/bin/cli.js';

const FIXTURE_ROOT = new URL('./fixtures/', import.meta.url);

describe('fixtures', () => {
  const tests: [string, { dir: string; config?: string; output: `${string}.css`[] }][] = [
    ['color', { dir: 'type-color', output: ['index.css'] }],
    ['dimension', { dir: 'type-dimension', output: ['index.css'] }],
    ['border', { dir: 'type-border', output: ['index.css'] }],
    ['gradient', { dir: 'type-gradient', output: ['index.css'] }],
    ['shadow', { dir: 'type-shadow', output: ['index.css'] }],
    ['transition', { dir: 'type-transition', output: ['index.css'] }],
    ['typography', { dir: 'type-typography', output: ['index.css'] }],
    ['string', { dir: 'type-string', output: ['index.css'] }],
    ['boolean', { dir: 'type-boolean', output: ['index.css'] }],
    ['color (legacy modes)', { dir: 'mode-type-color', output: ['index.css'] }],
    ['dimension (legacy modes)', { dir: 'mode-type-dimension', output: ['index.css'] }],
    ['border (legacy modes)', { dir: 'mode-type-border', output: ['index.css'] }],
    ['gradient (legacy modes)', { dir: 'mode-type-gradient', output: ['index.css'] }],
    ['shadow (legacy modes)', { dir: 'mode-type-shadow', output: ['index.css'] }],
    ['transition (legacy modes)', { dir: 'mode-type-transition', output: ['index.css'] }],
    ['typography (legacy modes)', { dir: 'mode-type-typography', output: ['index.css'] }],
    ['string (legacy modes)', { dir: 'mode-type-string', output: ['index.css'] }],
    ['boolean (legacy modes)', { dir: 'mode-type-boolean', output: ['index.css'] }],
    ['permutations with include', { dir: 'permutations-include', output: ['index.css'] }],
    ['yaml', { dir: 'yaml', output: ['index.css'] }],
    ['option: outDir', { dir: 'option-out-dir', output: ['styles/out/custom.css'] }],
    ['option: legacyHex', { dir: 'option-legacy-hex', output: ['index.css'] }],
    ['option: modeSelectors (legacy)', { dir: 'option-mode-selectors-chained-selector', output: ['index.css'] }],
    ['option: transform (manual hex)', { dir: 'option-transform-hex', output: ['index.css'] }],
    ['option: transform (exclude tokens)', { dir: 'option-transform-exclude', output: ['index.css'] }],
    ['option: transform (per permutation)', { dir: 'option-transform-per-permutation', output: ['index.css'] }],
    ['option: utility', { dir: 'option-utility', output: ['utility.css'] }],
    ['option: utility (legacy modes)', { dir: 'option-utility-modes', output: ['utility.css'] }],
    ['option: baseSelector (deprecated)', { dir: 'option-base-selector', output: ['index.css'] }],
    ['option: colorScheme (deprecated)', { dir: 'option-color-scheme', output: ['index.css'] }],
    ['DS: Adobe Spectrum', { dir: 'ds-adobe-spectrum', output: ['spectrum.css'] }],
    ['DS: Figma SDS', { dir: 'ds-figma-sds', output: ['sds.css'] }],
    ['DS: GitHub Primer', { dir: 'ds-github-primer', output: ['primer.css'] }],
    ['DS: Microsoft Fluent', { dir: 'ds-microsoft-fluent', output: ['fluent.css'] }],
  ];

  it.each(tests)('%s', async (_, { dir, config, output }) => {
    const cwd = new URL(dir.replace(/\/?$/, '/'), FIXTURE_ROOT);
    await execaNode({ cwd })`${cmd} build${config ? ` -c ${config}` : ''}`;
    for (const file of output) {
      await expect(await fs.readFile(new URL(file, cwd), 'utf8')).toMatchFileSnapshot(
        fileURLToPath(new URL(file.replace(/\.css$/, '.want.css'), cwd)),
      );
    }
  });
});

describe('CLI', () => {
  it('--watch', async () => {
    // note: this test is identical to "default"; just duplicated so 2 tests can
    // touch the filesystem without conflicting
    const cwd = new URL('./fixtures/cli-watch/', import.meta.url);
    const testFile = new URL('./tokens/index.css', cwd);

    try {
      // `--watch` will never terminate, so we want to cancel it after the file is created.
      // execa recommends AbortController rather than child.kill() for better cleanup.
      const controller = new AbortController();
      execaNode({
        cwd,
        cancelSignal: controller.signal,
        gracefulCancel: true,
        forceKillAfterDelay: false,
      })`${cmd} build --watch`;

      // poll for file creation (note: Vitest will handle timeouts)
      await new Promise((resolve) => {
        setInterval(() => {
          if (fsSync.existsSync(testFile)) {
            resolve(undefined);
          }
        }, 100);
      });

      // abort process (preferred over child.kill()
      controller.abort();
    } catch {
      // noop
    }

    // expect file isn’t empty
    expect(await fs.readFile(testFile, 'utf8')).toEqual(
      expect.stringContaining(`/* -------------------------------------------
 *  Autogenerated by ⛋ Terrazzo. DO NOT EDIT!
 * ------------------------------------------- */`),
    );
  }, 20_000);

  describe('options', () => {
    // Note: separate test because this no output is actually desired
    it('skipBuild', async () => {
      const cwd = new URL('./fixtures/option-skip-build/', import.meta.url);
      const before = await fs.readdir(cwd);
      await execaNode({ cwd })`${cmd} build`;
      const after = await fs.readdir(cwd);
      // assert absolutely no files or folders were created
      expect(after.length, `${after.length - before.length} file/folder(s) generated`).toBe(before.length);
    }, 20_000);
  });
});
