/**
 * Design Tokens
 * Autogenerated from tokens.json.
 * DO NOT EDIT!
 */

export const tokens = {
  'color.systemBlue': '#007aff',
  'color.systemBrown': '#a2845e',
  'color.systemCyan': '#32ade6',
  'color.systemGray': '#8e8e93',
  'color.systemGray2': '#aeaeb2',
  'color.systemGray3': '#c7c7cc',
  'color.systemGray4': '#d1d1d6',
  'color.systemGray5': '#e5e5ea',
  'color.systemGray6': '#f2f2f7',
  'color.systemGreen': '#34c759',
  'color.systemIndigo': '#5856d6',
  'color.systemMint': '#00c7be',
  'color.systemOrange': '#ff9500',
  'color.systemPurple': '#af52de',
  'color.systemPink': '#ff2d55',
  'color.systemRed': '#ff3b30',
  'color.systemTeal': '#30b0c7',
  'color.systemYellow': '#ffcc00',
  'font.family.sfPro': ['SF Pro'],
  'font.family.sfProRounded': ['SF Pro Rounded'],
  'font.family.sfCompact': ['SF Compact'],
  'font.family.sfMono': ['SF Mono'],
  'font.family.newYork': ['New York'],
  'font.style.largeTitle': {
    fontSize: '34px',
    fontWeight: 400,
    lineHeight: '41px',
  },
  'font.style.title1': {
    fontSize: '28px',
    fontWeight: 400,
    lineHeight: '34px',
  },
  'font.style.title2': {
    fontSize: '22px',
    fontWeight: 400,
    lineHeight: '25px',
  },
  'font.style.title3': {
    fontSize: '20px',
    fontWeight: 400,
    lineHeight: '25px',
  },
  'font.style.headline': {
    fontSize: '17px',
    fontWeight: 600,
    lineHeight: '22px',
  },
  'font.style.body': {
    fontSize: '17px',
    fontWeight: 400,
    lineHeight: '22px',
  },
  'font.style.callout': {
    fontSize: '16px',
    fontWeight: 400,
    lineHeight: '21px',
  },
  'font.style.subhead': {
    fontSize: '15px',
    fontWeight: 400,
    lineHeight: '20px',
  },
  'font.style.footnote': {
    fontSize: '13px',
    fontWeight: 400,
    lineHeight: '18px',
  },
  'font.style.caption1': {
    fontSize: '12px',
    fontWeight: 400,
    lineHeight: '16px',
  },
  'font.style.caption_2': {
    fontSize: '11px',
    fontWeight: 400,
    lineHeight: '13px',
  },
};

export const meta = {
  'color.systemBlue': {
    '$name': 'Blue',
    '$value': '#007aff',
    '$extensions': {
      mode: {
        light: '#007aff',
        dark: '#0a84ff',
        'light_ax': '#0040dd',
        'dark_ax': '#409cff',
      },
    },
  },
  'color.systemBrown': {
    '$name': 'Brown',
    '$value': '#a2845e',
    '$extensions': {
      mode: {
        light: '#a2845e',
        dark: '#ac8e68',
        'light_ax': '#7f6545',
        'dark_ax': '#b59469',
      },
    },
  },
  'color.systemCyan': {
    '$name': 'Cyan',
    '$value': '#32ade6',
    '$extensions': {
      mode: {
        light: '#32ade6',
        dark: '#64d2ff',
        'light_ax': '#0071a4',
        'dark_ax': '#70d7ff',
      },
    },
  },
  'color.systemGray': {
    '$name': 'Gray',
    '$value': '#8e8e93',
    '$extensions': {
      mode: {
        light: '#8e8e93',
        dark: '#8e8e93',
        'light_ax': '#6c6c70',
        'dark_ax': '#aeaeb2',
      },
    },
  },
  'color.systemGray2': {
    '$name': 'Gray (2)',
    '$value': '#aeaeb2',
    '$extensions': {
      mode: {
        light: '#aeaeb2',
        dark: '#636366',
        'light_ax': '#8e8e93',
        'dark_ax': '#7c7c80',
      },
    },
  },
  'color.systemGray3': {
    '$name': 'Gray (3)',
    '$value': '#c7c7cc',
    '$extensions': {
      mode: {
        light: '#c7c7cc',
        dark: '#48484a',
        'light_ax': '#aeaeb2',
        'dark_ax': '#545456',
      },
    },
  },
  'color.systemGray4': {
    '$name': 'Gray (4)',
    '$value': '#d1d1d6',
    '$extensions': {
      mode: {
        light: '#d1d1d6',
        dark: '#3a3a3c',
        'light_ax': '#bcbcc0',
        'dark_ax': '#444446',
      },
    },
  },
  'color.systemGray5': {
    '$name': 'Gray (5)',
    '$value': '#e5e5ea',
    '$extensions': {
      mode: {
        light: '#e5e5ea',
        dark: '#2c2c2e',
        'light_ax': '#d8d8dc',
        'dark_ax': '#363638',
      },
    },
  },
  'color.systemGray6': {
    '$name': 'Gray (6)',
    '$value': '#f2f2f7',
    '$extensions': {
      mode: {
        light: '#f2f2f7',
        dark: '#1c1c1e',
        'light_ax': '#ebebf0',
        'dark_ax': '#242426',
      },
    },
  },
  'color.systemGreen': {
    '$name': 'Green',
    '$value': '#34c759',
    '$extensions': {
      mode: {
        light: '#34c759',
        dark: '#30d158',
        'light_ax': '#248a3d',
        'dark_ax': '#30db5b',
      },
    },
  },
  'color.systemIndigo': {
    '$name': 'Indigo',
    '$value': '#5856d6',
    '$extensions': {
      mode: {
        light: '#5856d6',
        dark: '#5e5ce6',
        'light_ax': '#3634a3',
        'dark_ax': '#7d7aff',
      },
    },
  },
  'color.systemMint': {
    '$name': 'Mint',
    '$value': '#00c7be',
    '$extensions': {
      mode: {
        light: '#00c7be',
        dark: '#66d4cf',
        'light_ax': '#0c817b',
        'dark_ax': '#66d4cf',
      },
    },
  },
  'color.systemOrange': {
    '$name': 'Orange',
    '$value': '#ff9500',
    '$extensions': {
      mode: {
        light: '#ff9500',
        dark: '#ff9f0a',
        'light_ax': '#c93400',
        'dark_ax': '#ffb340',
      },
    },
  },
  'color.systemPurple': {
    '$name': 'Purple',
    '$value': '#af52de',
    '$extensions': {
      mode: {
        light: '#af52de',
        dark: '#bf5af2',
        'light_ax': '#8944ab',
        'dark_ax': '#da8fff',
      },
    },
  },
  'color.systemPink': {
    '$name': 'Pink',
    '$value': '#ff2d55',
    '$extensions': {
      mode: {
        light: '#ff2d55',
        dark: '#ff375f',
        'light_ax': '#d30f45',
        'dark_ax': '#ff6482',
      },
    },
  },
  'color.systemRed': {
    '$name': 'Red',
    '$value': '#ff3b30',
    '$extensions': {
      mode: {
        light: '#ff3b30',
        dark: '#ff453a',
        'light_ax': '#d70015',
        'dark_ax': '#ff6961',
      },
    },
  },
  'color.systemTeal': {
    '$name': 'Teal',
    '$value': '#30b0c7',
    '$extensions': {
      mode: {
        light: '#30b0c7',
        dark: '#40c8e0',
        'light_ax': '#008299',
        'dark_ax': '#5de6ff',
      },
    },
  },
  'color.systemYellow': {
    '$name': 'Yellow',
    '$value': '#ffcc00',
    '$extensions': {
      mode: {
        light: '#ffcc00',
        dark: '#ffd60a',
        'light_ax': '#b25000',
        'dark_ax': '#ffd426',
      },
    },
  },
  'font.family.sfPro': {
    '$value': 'SF Pro',
  },
  'font.family.sfProRounded': {
    '$value': 'SF Pro Rounded',
  },
  'font.family.sfCompact': {
    '$value': 'SF Compact',
  },
  'font.family.sfMono': {
    '$value': 'SF Mono',
  },
  'font.family.newYork': {
    '$value': 'New York',
  },
  'font.style.largeTitle': {
    '$value': {
      fontSize: '34px',
      fontWeight: 400,
      lineHeight: '41px',
    },
    '$extensions': {
      mode: {
        xSmall: {
          fontSize: '31px',
          lineHeight: '38px',
        },
        Small: {
          fontSize: '32px',
          lineHeight: '39px',
        },
        Medium: {
          fontSize: '33px',
          lineHeight: '40px',
        },
        Large: {
          fontSize: '34px',
          lineHeight: '41px',
        },
        xLarge: {
          fontSize: '36px',
          lineHeight: '43px',
        },
        xxLarge: {
          fontSize: '38px',
          lineHeight: '46px',
        },
        xxxLarge: {
          fontSize: '40px',
          lineHeight: '48px',
        },
      },
    },
  },
  'font.style.title1': {
    '$value': {
      fontSize: '28px',
      fontWeight: 400,
      lineHeight: '34px',
    },
    '$extensions': {
      mode: {
        xSmall: {
          fontSize: '25px',
          lineHeight: '31px',
        },
        Small: {
          fontSize: '26px',
          lineHeight: '32px',
        },
        Medium: {
          fontSize: '27px',
          lineHeight: '33px',
        },
        Large: {
          fontSize: '28px',
          lineHeight: '34px',
        },
        xLarge: {
          fontSize: '30px',
          lineHeight: '37px',
        },
        xxLarge: {
          fontSize: '32px',
          lineHeight: '39px',
        },
        xxxLarge: {
          fontSize: '32px',
          lineHeight: '41px',
        },
      },
    },
  },
  'font.style.title2': {
    '$value': {
      fontSize: '22px',
      fontWeight: 400,
      lineHeight: '25px',
    },
    '$extensions': {
      mode: {
        xSmall: {
          fontSize: '19px',
          lineHeight: '24px',
        },
        Small: {
          fontSize: '20px',
          lineHeight: '25px',
        },
        Medium: {
          fontSize: '21px',
          lineHeight: '26px',
        },
        Large: {
          fontSize: '22px',
          lineHeight: '28px',
        },
        xLarge: {
          fontSize: '24px',
          lineHeight: '30px',
        },
        xxLarge: {
          fontSize: '26px',
          lineHeight: '32px',
        },
        xxxLarge: {
          fontSize: '28px',
          lineHeight: '34px',
        },
      },
    },
  },
  'font.style.title3': {
    '$value': {
      fontSize: '20px',
      fontWeight: 400,
      lineHeight: '25px',
    },
    '$extensions': {
      mode: {
        xSmall: {
          fontSize: '25px',
          lineHeight: '22px',
        },
        Small: {
          fontSize: '26px',
          lineHeight: '23px',
        },
        Medium: {
          fontSize: '27px',
          lineHeight: '24px',
        },
        Large: {
          fontSize: '28px',
          lineHeight: '25px',
        },
        xLarge: {
          fontSize: '30px',
          lineHeight: '28px',
        },
        xxLarge: {
          fontSize: '32px',
          lineHeight: '30px',
        },
        xxxLarge: {
          fontSize: '32px',
          lineHeight: '32px',
        },
      },
    },
  },
  'font.style.headline': {
    '$value': {
      fontSize: '17px',
      fontWeight: 600,
      lineHeight: '22px',
    },
    '$extensions': {
      mode: {
        xSmall: {
          fontSize: '14px',
          lineHeight: '19px',
        },
        Small: {
          fontSize: '15px',
          lineHeight: '20px',
        },
        Medium: {
          fontSize: '16px',
          lineHeight: '21px',
        },
        Large: {
          fontSize: '17px',
          lineHeight: '22px',
        },
        xLarge: {
          fontSize: '19px',
          lineHeight: '24px',
        },
        xxLarge: {
          fontSize: '21px',
          lineHeight: '26px',
        },
        xxxLarge: {
          fontSize: '23px',
          lineHeight: '29px',
        },
      },
    },
  },
  'font.style.body': {
    '$value': {
      fontSize: '17px',
      fontWeight: 400,
      lineHeight: '22px',
    },
    '$extensions': {
      mode: {
        xSmall: {
          fontSize: '14px',
          lineHeight: '19px',
        },
        Small: {
          fontSize: '15px',
          lineHeight: '20px',
        },
        Medium: {
          fontSize: '16px',
          lineHeight: '21px',
        },
        Large: {
          fontSize: '17px',
          lineHeight: '22px',
        },
        xLarge: {
          fontSize: '19px',
          lineHeight: '24px',
        },
        xxLarge: {
          fontSize: '21px',
          lineHeight: '26px',
        },
        xxxLarge: {
          fontSize: '23px',
          lineHeight: '29px',
        },
      },
    },
  },
  'font.style.callout': {
    '$value': {
      fontSize: '16px',
      fontWeight: 400,
      lineHeight: '21px',
    },
    '$extensions': {
      mode: {
        xSmall: {
          fontSize: '13px',
          lineHeight: '18px',
        },
        Small: {
          fontSize: '14px',
          lineHeight: '19px',
        },
        Medium: {
          fontSize: '15px',
          lineHeight: '20px',
        },
        Large: {
          fontSize: '16px',
          lineHeight: '21px',
        },
        xLarge: {
          fontSize: '18px',
          lineHeight: '23px',
        },
        xxLarge: {
          fontSize: '20px',
          lineHeight: '25px',
        },
        xxxLarge: {
          fontSize: '22px',
          lineHeight: '28px',
        },
      },
    },
  },
  'font.style.subhead': {
    '$value': {
      fontSize: '15px',
      fontWeight: 400,
      lineHeight: '20px',
    },
    '$extensions': {
      mode: {
        xSmall: {
          fontSize: '12px',
          lineHeight: '16px',
        },
        Small: {
          fontSize: '13px',
          lineHeight: '18px',
        },
        Medium: {
          fontSize: '14px',
          lineHeight: '19px',
        },
        Large: {
          fontSize: '15px',
          lineHeight: '20px',
        },
        xLarge: {
          fontSize: '17px',
          lineHeight: '22px',
        },
        xxLarge: {
          fontSize: '19px',
          lineHeight: '24px',
        },
        xxxLarge: {
          fontSize: '21px',
          lineHeight: '28px',
        },
      },
    },
  },
  'font.style.footnote': {
    '$value': {
      fontSize: '13px',
      fontWeight: 400,
      lineHeight: '18px',
    },
    '$extensions': {
      mode: {
        xSmall: {
          fontSize: '12px',
          lineHeight: '16px',
        },
        Small: {
          fontSize: '12px',
          lineHeight: '16px',
        },
        Medium: {
          fontSize: '12px',
          lineHeight: '16px',
        },
        Large: {
          fontSize: '13px',
          lineHeight: '18px',
        },
        xLarge: {
          fontSize: '15px',
          lineHeight: '20px',
        },
        xxLarge: {
          fontSize: '17px',
          lineHeight: '22px',
        },
        xxxLarge: {
          fontSize: '19px',
          lineHeight: '24px',
        },
      },
    },
  },
  'font.style.caption1': {
    '$value': {
      fontSize: '12px',
      fontWeight: 400,
      lineHeight: '16px',
    },
    '$extensions': {
      mode: {
        xSmall: {
          fontSize: '11px',
          lineHeight: '13px',
        },
        Small: {
          fontSize: '11px',
          lineHeight: '13px',
        },
        Medium: {
          fontSize: '11px',
          lineHeight: '13px',
        },
        Large: {
          fontSize: '12px',
          lineHeight: '16px',
        },
        xLarge: {
          fontSize: '14px',
          lineHeight: '19px',
        },
        xxLarge: {
          fontSize: '16px',
          lineHeight: '18px',
        },
        xxxLarge: {
          fontSize: '23px',
          lineHeight: '21px',
        },
      },
    },
  },
  'font.style.caption_2': {
    '$value': {
      fontSize: '11px',
      fontWeight: 400,
      lineHeight: '13px',
    },
    '$extensions': {
      mode: {
        xSmall: {
          fontSize: '11px',
          lineHeight: '13px',
        },
        Small: {
          fontSize: '11px',
          lineHeight: '13px',
        },
        Medium: {
          fontSize: '11px',
          lineHeight: '13px',
        },
        Large: {
          fontSize: '11px',
          lineHeight: '13px',
        },
        xLarge: {
          fontSize: '13px',
          lineHeight: '18px',
        },
        xxLarge: {
          fontSize: '15px',
          lineHeight: '20px',
        },
        xxxLarge: {
          fontSize: '17px',
          lineHeight: '22px',
        },
      },
    },
  },
};

export const modes = {
  'color.systemBlue': {
    light: '#007aff',
    dark: '#0a84ff',
    'light_ax': '#0040dd',
    'dark_ax': '#409cff',
  },
  'color.systemBrown': {
    light: '#a2845e',
    dark: '#ac8e68',
    'light_ax': '#7f6545',
    'dark_ax': '#b59469',
  },
  'color.systemCyan': {
    light: '#32ade6',
    dark: '#64d2ff',
    'light_ax': '#0071a4',
    'dark_ax': '#70d7ff',
  },
  'color.systemGray': {
    light: '#8e8e93',
    dark: '#8e8e93',
    'light_ax': '#6c6c70',
    'dark_ax': '#aeaeb2',
  },
  'color.systemGray2': {
    light: '#aeaeb2',
    dark: '#636366',
    'light_ax': '#8e8e93',
    'dark_ax': '#7c7c80',
  },
  'color.systemGray3': {
    light: '#c7c7cc',
    dark: '#48484a',
    'light_ax': '#aeaeb2',
    'dark_ax': '#545456',
  },
  'color.systemGray4': {
    light: '#d1d1d6',
    dark: '#3a3a3c',
    'light_ax': '#bcbcc0',
    'dark_ax': '#444446',
  },
  'color.systemGray5': {
    light: '#e5e5ea',
    dark: '#2c2c2e',
    'light_ax': '#d8d8dc',
    'dark_ax': '#363638',
  },
  'color.systemGray6': {
    light: '#f2f2f7',
    dark: '#1c1c1e',
    'light_ax': '#ebebf0',
    'dark_ax': '#242426',
  },
  'color.systemGreen': {
    light: '#34c759',
    dark: '#30d158',
    'light_ax': '#248a3d',
    'dark_ax': '#30db5b',
  },
  'color.systemIndigo': {
    light: '#5856d6',
    dark: '#5e5ce6',
    'light_ax': '#3634a3',
    'dark_ax': '#7d7aff',
  },
  'color.systemMint': {
    light: '#00c7be',
    dark: '#66d4cf',
    'light_ax': '#0c817b',
    'dark_ax': '#66d4cf',
  },
  'color.systemOrange': {
    light: '#ff9500',
    dark: '#ff9f0a',
    'light_ax': '#c93400',
    'dark_ax': '#ffb340',
  },
  'color.systemPurple': {
    light: '#af52de',
    dark: '#bf5af2',
    'light_ax': '#8944ab',
    'dark_ax': '#da8fff',
  },
  'color.systemPink': {
    light: '#ff2d55',
    dark: '#ff375f',
    'light_ax': '#d30f45',
    'dark_ax': '#ff6482',
  },
  'color.systemRed': {
    light: '#ff3b30',
    dark: '#ff453a',
    'light_ax': '#d70015',
    'dark_ax': '#ff6961',
  },
  'color.systemTeal': {
    light: '#30b0c7',
    dark: '#40c8e0',
    'light_ax': '#008299',
    'dark_ax': '#5de6ff',
  },
  'color.systemYellow': {
    light: '#ffcc00',
    dark: '#ffd60a',
    'light_ax': '#b25000',
    'dark_ax': '#ffd426',
  },
  'font.style.largeTitle': {
    xSmall: {
      fontSize: '31px',
      lineHeight: '38px',
    },
    Small: {
      fontSize: '32px',
      lineHeight: '39px',
    },
    Medium: {
      fontSize: '33px',
      lineHeight: '40px',
    },
    Large: {
      fontSize: '34px',
      lineHeight: '41px',
    },
    xLarge: {
      fontSize: '36px',
      lineHeight: '43px',
    },
    xxLarge: {
      fontSize: '38px',
      lineHeight: '46px',
    },
    xxxLarge: {
      fontSize: '40px',
      lineHeight: '48px',
    },
  },
  'font.style.title1': {
    xSmall: {
      fontSize: '25px',
      lineHeight: '31px',
    },
    Small: {
      fontSize: '26px',
      lineHeight: '32px',
    },
    Medium: {
      fontSize: '27px',
      lineHeight: '33px',
    },
    Large: {
      fontSize: '28px',
      lineHeight: '34px',
    },
    xLarge: {
      fontSize: '30px',
      lineHeight: '37px',
    },
    xxLarge: {
      fontSize: '32px',
      lineHeight: '39px',
    },
    xxxLarge: {
      fontSize: '32px',
      lineHeight: '41px',
    },
  },
  'font.style.title2': {
    xSmall: {
      fontSize: '19px',
      lineHeight: '24px',
    },
    Small: {
      fontSize: '20px',
      lineHeight: '25px',
    },
    Medium: {
      fontSize: '21px',
      lineHeight: '26px',
    },
    Large: {
      fontSize: '22px',
      lineHeight: '28px',
    },
    xLarge: {
      fontSize: '24px',
      lineHeight: '30px',
    },
    xxLarge: {
      fontSize: '26px',
      lineHeight: '32px',
    },
    xxxLarge: {
      fontSize: '28px',
      lineHeight: '34px',
    },
  },
  'font.style.title3': {
    xSmall: {
      fontSize: '25px',
      lineHeight: '22px',
    },
    Small: {
      fontSize: '26px',
      lineHeight: '23px',
    },
    Medium: {
      fontSize: '27px',
      lineHeight: '24px',
    },
    Large: {
      fontSize: '28px',
      lineHeight: '25px',
    },
    xLarge: {
      fontSize: '30px',
      lineHeight: '28px',
    },
    xxLarge: {
      fontSize: '32px',
      lineHeight: '30px',
    },
    xxxLarge: {
      fontSize: '32px',
      lineHeight: '32px',
    },
  },
  'font.style.headline': {
    xSmall: {
      fontSize: '14px',
      lineHeight: '19px',
    },
    Small: {
      fontSize: '15px',
      lineHeight: '20px',
    },
    Medium: {
      fontSize: '16px',
      lineHeight: '21px',
    },
    Large: {
      fontSize: '17px',
      lineHeight: '22px',
    },
    xLarge: {
      fontSize: '19px',
      lineHeight: '24px',
    },
    xxLarge: {
      fontSize: '21px',
      lineHeight: '26px',
    },
    xxxLarge: {
      fontSize: '23px',
      lineHeight: '29px',
    },
  },
  'font.style.body': {
    xSmall: {
      fontSize: '14px',
      lineHeight: '19px',
    },
    Small: {
      fontSize: '15px',
      lineHeight: '20px',
    },
    Medium: {
      fontSize: '16px',
      lineHeight: '21px',
    },
    Large: {
      fontSize: '17px',
      lineHeight: '22px',
    },
    xLarge: {
      fontSize: '19px',
      lineHeight: '24px',
    },
    xxLarge: {
      fontSize: '21px',
      lineHeight: '26px',
    },
    xxxLarge: {
      fontSize: '23px',
      lineHeight: '29px',
    },
  },
  'font.style.callout': {
    xSmall: {
      fontSize: '13px',
      lineHeight: '18px',
    },
    Small: {
      fontSize: '14px',
      lineHeight: '19px',
    },
    Medium: {
      fontSize: '15px',
      lineHeight: '20px',
    },
    Large: {
      fontSize: '16px',
      lineHeight: '21px',
    },
    xLarge: {
      fontSize: '18px',
      lineHeight: '23px',
    },
    xxLarge: {
      fontSize: '20px',
      lineHeight: '25px',
    },
    xxxLarge: {
      fontSize: '22px',
      lineHeight: '28px',
    },
  },
  'font.style.subhead': {
    xSmall: {
      fontSize: '12px',
      lineHeight: '16px',
    },
    Small: {
      fontSize: '13px',
      lineHeight: '18px',
    },
    Medium: {
      fontSize: '14px',
      lineHeight: '19px',
    },
    Large: {
      fontSize: '15px',
      lineHeight: '20px',
    },
    xLarge: {
      fontSize: '17px',
      lineHeight: '22px',
    },
    xxLarge: {
      fontSize: '19px',
      lineHeight: '24px',
    },
    xxxLarge: {
      fontSize: '21px',
      lineHeight: '28px',
    },
  },
  'font.style.footnote': {
    xSmall: {
      fontSize: '12px',
      lineHeight: '16px',
    },
    Small: {
      fontSize: '12px',
      lineHeight: '16px',
    },
    Medium: {
      fontSize: '12px',
      lineHeight: '16px',
    },
    Large: {
      fontSize: '13px',
      lineHeight: '18px',
    },
    xLarge: {
      fontSize: '15px',
      lineHeight: '20px',
    },
    xxLarge: {
      fontSize: '17px',
      lineHeight: '22px',
    },
    xxxLarge: {
      fontSize: '19px',
      lineHeight: '24px',
    },
  },
  'font.style.caption1': {
    xSmall: {
      fontSize: '11px',
      lineHeight: '13px',
    },
    Small: {
      fontSize: '11px',
      lineHeight: '13px',
    },
    Medium: {
      fontSize: '11px',
      lineHeight: '13px',
    },
    Large: {
      fontSize: '12px',
      lineHeight: '16px',
    },
    xLarge: {
      fontSize: '14px',
      lineHeight: '19px',
    },
    xxLarge: {
      fontSize: '16px',
      lineHeight: '18px',
    },
    xxxLarge: {
      fontSize: '23px',
      lineHeight: '21px',
    },
  },
  'font.style.caption_2': {
    xSmall: {
      fontSize: '11px',
      lineHeight: '13px',
    },
    Small: {
      fontSize: '11px',
      lineHeight: '13px',
    },
    Medium: {
      fontSize: '11px',
      lineHeight: '13px',
    },
    Large: {
      fontSize: '11px',
      lineHeight: '13px',
    },
    xLarge: {
      fontSize: '13px',
      lineHeight: '18px',
    },
    xxLarge: {
      fontSize: '15px',
      lineHeight: '20px',
    },
    xxxLarge: {
      fontSize: '17px',
      lineHeight: '22px',
    },
  },
};

/** Get individual token */
export function token(tokenID, modeName) {
  if (modeName && modes[tokenID] && modeName in modes[tokenID]) return modes[tokenID][modeName];
  return tokens[tokenID];
}
