/**
 * Design Tokens
 * Autogenerated from tokens.json.
 * DO NOT EDIT!
 */

import {
  ColorToken,
  FontToken,
  ParsedColorToken,
  ParsedFontToken,
  ParsedTypographyToken,
  TypographyToken,
} from '@cobalt-ui/core';

export declare const tokens: {
  'color.systemBlue': ColorToken['$value'];
  'color.systemBrown': ColorToken['$value'];
  'color.systemCyan': ColorToken['$value'];
  'color.systemGray': ColorToken['$value'];
  'color.systemGray2': ColorToken['$value'];
  'color.systemGray3': ColorToken['$value'];
  'color.systemGray4': ColorToken['$value'];
  'color.systemGray5': ColorToken['$value'];
  'color.systemGray6': ColorToken['$value'];
  'color.systemGreen': ColorToken['$value'];
  'color.systemIndigo': ColorToken['$value'];
  'color.systemMint': ColorToken['$value'];
  'color.systemOrange': ColorToken['$value'];
  'color.systemPurple': ColorToken['$value'];
  'color.systemPink': ColorToken['$value'];
  'color.systemRed': ColorToken['$value'];
  'color.systemTeal': ColorToken['$value'];
  'color.systemYellow': ColorToken['$value'];
  'font.family.sfPro': FontToken['$value'];
  'font.family.sfProRounded': FontToken['$value'];
  'font.family.sfCompact': FontToken['$value'];
  'font.family.sfMono': FontToken['$value'];
  'font.family.newYork': FontToken['$value'];
  'font.style.largeTitle': TypographyToken['$value'];
  'font.style.title1': TypographyToken['$value'];
  'font.style.title2': TypographyToken['$value'];
  'font.style.title3': TypographyToken['$value'];
  'font.style.headline': TypographyToken['$value'];
  'font.style.body': TypographyToken['$value'];
  'font.style.callout': TypographyToken['$value'];
  'font.style.subhead': TypographyToken['$value'];
  'font.style.footnote': TypographyToken['$value'];
  'font.style.caption1': TypographyToken['$value'];
  'font.style.caption_2': TypographyToken['$value'];
};

export declare const meta: {
  'color.systemBlue': ParsedColorToken & { $extensions: { mode: typeof modes['color.systemBlue'] } };
  'color.systemBrown': ParsedColorToken & { $extensions: { mode: typeof modes['color.systemBrown'] } };
  'color.systemCyan': ParsedColorToken & { $extensions: { mode: typeof modes['color.systemCyan'] } };
  'color.systemGray': ParsedColorToken & { $extensions: { mode: typeof modes['color.systemGray'] } };
  'color.systemGray2': ParsedColorToken & { $extensions: { mode: typeof modes['color.systemGray2'] } };
  'color.systemGray3': ParsedColorToken & { $extensions: { mode: typeof modes['color.systemGray3'] } };
  'color.systemGray4': ParsedColorToken & { $extensions: { mode: typeof modes['color.systemGray4'] } };
  'color.systemGray5': ParsedColorToken & { $extensions: { mode: typeof modes['color.systemGray5'] } };
  'color.systemGray6': ParsedColorToken & { $extensions: { mode: typeof modes['color.systemGray6'] } };
  'color.systemGreen': ParsedColorToken & { $extensions: { mode: typeof modes['color.systemGreen'] } };
  'color.systemIndigo': ParsedColorToken & { $extensions: { mode: typeof modes['color.systemIndigo'] } };
  'color.systemMint': ParsedColorToken & { $extensions: { mode: typeof modes['color.systemMint'] } };
  'color.systemOrange': ParsedColorToken & { $extensions: { mode: typeof modes['color.systemOrange'] } };
  'color.systemPurple': ParsedColorToken & { $extensions: { mode: typeof modes['color.systemPurple'] } };
  'color.systemPink': ParsedColorToken & { $extensions: { mode: typeof modes['color.systemPink'] } };
  'color.systemRed': ParsedColorToken & { $extensions: { mode: typeof modes['color.systemRed'] } };
  'color.systemTeal': ParsedColorToken & { $extensions: { mode: typeof modes['color.systemTeal'] } };
  'color.systemYellow': ParsedColorToken & { $extensions: { mode: typeof modes['color.systemYellow'] } };
  'font.family.sfPro': ParsedFontToken;
  'font.family.sfProRounded': ParsedFontToken;
  'font.family.sfCompact': ParsedFontToken;
  'font.family.sfMono': ParsedFontToken;
  'font.family.newYork': ParsedFontToken;
  'font.style.largeTitle': ParsedTypographyToken & { $extensions: { mode: typeof modes['font.style.largeTitle'] } };
  'font.style.title1': ParsedTypographyToken & { $extensions: { mode: typeof modes['font.style.title1'] } };
  'font.style.title2': ParsedTypographyToken & { $extensions: { mode: typeof modes['font.style.title2'] } };
  'font.style.title3': ParsedTypographyToken & { $extensions: { mode: typeof modes['font.style.title3'] } };
  'font.style.headline': ParsedTypographyToken & { $extensions: { mode: typeof modes['font.style.headline'] } };
  'font.style.body': ParsedTypographyToken & { $extensions: { mode: typeof modes['font.style.body'] } };
  'font.style.callout': ParsedTypographyToken & { $extensions: { mode: typeof modes['font.style.callout'] } };
  'font.style.subhead': ParsedTypographyToken & { $extensions: { mode: typeof modes['font.style.subhead'] } };
  'font.style.footnote': ParsedTypographyToken & { $extensions: { mode: typeof modes['font.style.footnote'] } };
  'font.style.caption1': ParsedTypographyToken & { $extensions: { mode: typeof modes['font.style.caption1'] } };
  'font.style.caption_2': ParsedTypographyToken & { $extensions: { mode: typeof modes['font.style.caption_2'] } };
};

export declare const modes: {
  'color.systemBlue': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
    'light_ax': ColorToken['$value'];
    'dark_ax': ColorToken['$value'];
  };
  'color.systemBrown': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
    'light_ax': ColorToken['$value'];
    'dark_ax': ColorToken['$value'];
  };
  'color.systemCyan': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
    'light_ax': ColorToken['$value'];
    'dark_ax': ColorToken['$value'];
  };
  'color.systemGray': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
    'light_ax': ColorToken['$value'];
    'dark_ax': ColorToken['$value'];
  };
  'color.systemGray2': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
    'light_ax': ColorToken['$value'];
    'dark_ax': ColorToken['$value'];
  };
  'color.systemGray3': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
    'light_ax': ColorToken['$value'];
    'dark_ax': ColorToken['$value'];
  };
  'color.systemGray4': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
    'light_ax': ColorToken['$value'];
    'dark_ax': ColorToken['$value'];
  };
  'color.systemGray5': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
    'light_ax': ColorToken['$value'];
    'dark_ax': ColorToken['$value'];
  };
  'color.systemGray6': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
    'light_ax': ColorToken['$value'];
    'dark_ax': ColorToken['$value'];
  };
  'color.systemGreen': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
    'light_ax': ColorToken['$value'];
    'dark_ax': ColorToken['$value'];
  };
  'color.systemIndigo': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
    'light_ax': ColorToken['$value'];
    'dark_ax': ColorToken['$value'];
  };
  'color.systemMint': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
    'light_ax': ColorToken['$value'];
    'dark_ax': ColorToken['$value'];
  };
  'color.systemOrange': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
    'light_ax': ColorToken['$value'];
    'dark_ax': ColorToken['$value'];
  };
  'color.systemPurple': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
    'light_ax': ColorToken['$value'];
    'dark_ax': ColorToken['$value'];
  };
  'color.systemPink': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
    'light_ax': ColorToken['$value'];
    'dark_ax': ColorToken['$value'];
  };
  'color.systemRed': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
    'light_ax': ColorToken['$value'];
    'dark_ax': ColorToken['$value'];
  };
  'color.systemTeal': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
    'light_ax': ColorToken['$value'];
    'dark_ax': ColorToken['$value'];
  };
  'color.systemYellow': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
    'light_ax': ColorToken['$value'];
    'dark_ax': ColorToken['$value'];
  };
  'font.style.largeTitle': {
    xSmall: TypographyToken['$value'];
    Small: TypographyToken['$value'];
    Medium: TypographyToken['$value'];
    Large: TypographyToken['$value'];
    xLarge: TypographyToken['$value'];
    xxLarge: TypographyToken['$value'];
    xxxLarge: TypographyToken['$value'];
  };
  'font.style.title1': {
    xSmall: TypographyToken['$value'];
    Small: TypographyToken['$value'];
    Medium: TypographyToken['$value'];
    Large: TypographyToken['$value'];
    xLarge: TypographyToken['$value'];
    xxLarge: TypographyToken['$value'];
    xxxLarge: TypographyToken['$value'];
  };
  'font.style.title2': {
    xSmall: TypographyToken['$value'];
    Small: TypographyToken['$value'];
    Medium: TypographyToken['$value'];
    Large: TypographyToken['$value'];
    xLarge: TypographyToken['$value'];
    xxLarge: TypographyToken['$value'];
    xxxLarge: TypographyToken['$value'];
  };
  'font.style.title3': {
    xSmall: TypographyToken['$value'];
    Small: TypographyToken['$value'];
    Medium: TypographyToken['$value'];
    Large: TypographyToken['$value'];
    xLarge: TypographyToken['$value'];
    xxLarge: TypographyToken['$value'];
    xxxLarge: TypographyToken['$value'];
  };
  'font.style.headline': {
    xSmall: TypographyToken['$value'];
    Small: TypographyToken['$value'];
    Medium: TypographyToken['$value'];
    Large: TypographyToken['$value'];
    xLarge: TypographyToken['$value'];
    xxLarge: TypographyToken['$value'];
    xxxLarge: TypographyToken['$value'];
  };
  'font.style.body': {
    xSmall: TypographyToken['$value'];
    Small: TypographyToken['$value'];
    Medium: TypographyToken['$value'];
    Large: TypographyToken['$value'];
    xLarge: TypographyToken['$value'];
    xxLarge: TypographyToken['$value'];
    xxxLarge: TypographyToken['$value'];
  };
  'font.style.callout': {
    xSmall: TypographyToken['$value'];
    Small: TypographyToken['$value'];
    Medium: TypographyToken['$value'];
    Large: TypographyToken['$value'];
    xLarge: TypographyToken['$value'];
    xxLarge: TypographyToken['$value'];
    xxxLarge: TypographyToken['$value'];
  };
  'font.style.subhead': {
    xSmall: TypographyToken['$value'];
    Small: TypographyToken['$value'];
    Medium: TypographyToken['$value'];
    Large: TypographyToken['$value'];
    xLarge: TypographyToken['$value'];
    xxLarge: TypographyToken['$value'];
    xxxLarge: TypographyToken['$value'];
  };
  'font.style.footnote': {
    xSmall: TypographyToken['$value'];
    Small: TypographyToken['$value'];
    Medium: TypographyToken['$value'];
    Large: TypographyToken['$value'];
    xLarge: TypographyToken['$value'];
    xxLarge: TypographyToken['$value'];
    xxxLarge: TypographyToken['$value'];
  };
  'font.style.caption1': {
    xSmall: TypographyToken['$value'];
    Small: TypographyToken['$value'];
    Medium: TypographyToken['$value'];
    Large: TypographyToken['$value'];
    xLarge: TypographyToken['$value'];
    xxLarge: TypographyToken['$value'];
    xxxLarge: TypographyToken['$value'];
  };
  'font.style.caption_2': {
    xSmall: TypographyToken['$value'];
    Small: TypographyToken['$value'];
    Medium: TypographyToken['$value'];
    Large: TypographyToken['$value'];
    xLarge: TypographyToken['$value'];
    xxLarge: TypographyToken['$value'];
    xxxLarge: TypographyToken['$value'];
  };
};

export declare function token(tokenID: keyof typeof tokens, modeName?: never): typeof tokens[typeof tokenID];
export declare function token(tokenID: keyof typeof modes, modeName?: keyof typeof modes[typeof tokenID]): typeof modes[typeof tokenID];
