import type { LintRuleShorthand, LintRuleLonghand, LintNotice, LintRule } from './lint/index.js';
import type Logger from './logger.js';

export interface Config {
  /** Path to tokens.json (default: "./tokens.json") */
  tokens?: string | string[];
  /** Output directory (default: "./tokens/") */
  outDir?: string;
  /** Specify plugins */
  plugins?: Plugin[];
  /** Specify linting settings */
  lint?: {
    /** Configure build behavior */
    build?: {
      /** Should linters run with `co build`? (default: true) */
      enabled?: boolean;
    };
    /** Configure lint rules */
    rules?: Record<string, LintRuleShorthand | LintRuleLonghand>;
  };
}

export interface ConfigInit {
  tokens: URL[];
  outDir: URL;
  plugins: Plugin[];
  lint: {
    build: NonNullable<NonNullable<Config['lint']>['build']>;
    rules: Record<string, LintRule>;
  };
}

export interface Plugin {
  name: string;
  /** (optional) Read config, and optionally modify */
  // biome-ignore lint/suspicious/noConfusingVoidType format: this helps plugins be a little looser on their typing
  config?(config: ConfigInit): void | ConfigInit | undefined;
  /** (optional) Register lint rule IDs */
  registerRules?(): Omit<LintRule, 'options'>[];
  /** (optional) Throw lint errors/warnings */
  lint?(options: PluginLintStageOptions): Promise<LintNotice[] | undefined>;
  /** Main build fn */
}

export interface PluginLintStageOptions {
  /**
   * The rules this plugin registered will be returned here, along with the user’s preset `severity` ("off" if they’ve disabled it)
   */
  rules: LintRule[];
  /**
   * Traversable AST generated by Momoa (gives you a way to point to the code that erred)
   */
  traverse: (visitor: any) => void;
}

export interface ConfigOptions {
  logger?: Logger;
  /** Configs need CWD so this can be run without Node.js */
  cwd: URL;
}

/**
 * Validate and normalize a config
 */
export default function validateAndNormalizeConfig(rawConfig: Config, options: ConfigOptions): ConfigInit;

export function mergeConfigs(a: Config, b: Config): Config;
