import { describe, expect, it } from 'vitest';
import fs from 'node:fs';
import { execa } from 'execa';
import stripAnsi from 'strip-ansi';

const cmd = '../../../bin/cli.js';

describe('tz build', () => {
  it('default', async () => {
    const cwd = new URL('./fixtures/build-default/', import.meta.url);
    await execa('node', [cmd, 'build'], { cwd });

    // expect generated file exists
    expect(fs.existsSync(new URL('./tokens/index.css', cwd))).toBe(true);
    // expect there
    expect(fs.readFileSync(new URL('./tokens/index.css', cwd), 'utf8')).toEqual(
      expect.stringContaining(`/* -------------------------------------------
 *  Autogenerated by ⛋ Terrazzo. DO NOT EDIT!
 * ------------------------------------------- */`),
    );
  });

  describe('errors', () => {
    const errors: [string, { cwd: string; want: string }][] = [
      [
        'no tokens',
        { cwd: 'error-no-tokens', want: '✘  Could not locate tokens.json. To create one, run `npx tz init`.' },
      ],
      [
        'config: no default export',
        {
          cwd: 'error-no-default-export',
          want: '✘  No default export found in terrazzo.config.js. See https://terrazzo.dev/docs/cli for instructions.',
        },
      ],
    ];

    it.each(errors)('%s', async (_, { cwd, want }) => {
      try {
        await execa('node', [cmd, 'build'], { cwd: new URL(`./fixtures/${cwd}/`, import.meta.url) });
        expect(true).toBe(false);
      } catch (err) {
        expect(stripAnsi((err as Error).message)).toMatch(want);
      }
    });
  });
});
