export const border = {
  1: 'var(--tz-border-1)',
  2: 'var(--tz-border-2)',
  3: 'var(--tz-border-3)',
  focus: 'var(--tz-border-focus)',
};
export const color = {
  base: {
    blue: {
      100: 'var(--tz-color-base-blue-100)',
      200: 'var(--tz-color-base-blue-200)',
      300: 'var(--tz-color-base-blue-300)',
      400: 'var(--tz-color-base-blue-400)',
      500: 'var(--tz-color-base-blue-500)',
      600: 'var(--tz-color-base-blue-600)',
      700: 'var(--tz-color-base-blue-700)',
      800: 'var(--tz-color-base-blue-800)',
      900: 'var(--tz-color-base-blue-900)',
      1000: 'var(--tz-color-base-blue-1000)',
    },
    gray: {
      100: 'var(--tz-color-base-gray-100)',
      200: 'var(--tz-color-base-gray-200)',
      300: 'var(--tz-color-base-gray-300)',
      400: 'var(--tz-color-base-gray-400)',
      500: 'var(--tz-color-base-gray-500)',
      600: 'var(--tz-color-base-gray-600)',
      700: 'var(--tz-color-base-gray-700)',
      800: 'var(--tz-color-base-gray-800)',
      900: 'var(--tz-color-base-gray-900)',
      950: 'var(--tz-color-base-gray-950)',
      1000: 'var(--tz-color-base-gray-1000)',
    },
    lime: {
      100: 'var(--tz-color-base-lime-100)',
      200: 'var(--tz-color-base-lime-200)',
      300: 'var(--tz-color-base-lime-300)',
      400: 'var(--tz-color-base-lime-400)',
      500: 'var(--tz-color-base-lime-500)',
      600: 'var(--tz-color-base-lime-600)',
      700: 'var(--tz-color-base-lime-700)',
      800: 'var(--tz-color-base-lime-800)',
      900: 'var(--tz-color-base-lime-900)',
      1000: 'var(--tz-color-base-lime-1000)',
    },
    orange: {
      100: 'var(--tz-color-base-orange-100)',
      200: 'var(--tz-color-base-orange-200)',
      300: 'var(--tz-color-base-orange-300)',
      400: 'var(--tz-color-base-orange-400)',
      500: 'var(--tz-color-base-orange-500)',
      600: 'var(--tz-color-base-orange-600)',
      700: 'var(--tz-color-base-orange-700)',
      800: 'var(--tz-color-base-orange-800)',
      900: 'var(--tz-color-base-orange-900)',
      1000: 'var(--tz-color-base-orange-1000)',
    },
  },
  bg: {
    1: 'var(--tz-color-bg-1)',
    2: 'var(--tz-color-bg-2)',
    3: 'var(--tz-color-bg-3)',
    error: 'var(--tz-color-bg-error)',
    selected: 'var(--tz-color-bg-selected)',
    selectedHint: 'var(--tz-color-bg-selected-hint)',
  },
  border: {
    1: 'var(--tz-color-border-1)',
    2: 'var(--tz-color-border-2)',
    3: 'var(--tz-color-border-3)',
    focus: 'var(--tz-color-border-focus)',
    selected: 'var(--tz-color-border-selected)',
  },
  icon: {
    100: 'var(--tz-color-icon-100)',
    200: 'var(--tz-color-icon-200)',
    selected: 'var(--tz-color-icon-selected)',
  },
  text: {
    1: 'var(--tz-color-text-1)',
    2: 'var(--tz-color-text-2)',
    3: 'var(--tz-color-text-3)',
    error: 'var(--tz-color-text-error)',
    selected: 'var(--tz-color-text-selected)',
  },
};
export const ease = {
  linear: 'var(--tz-ease-linear)',
  quintIn: 'var(--tz-ease-quint-in)',
  quintInOut: 'var(--tz-ease-quint-in-out)',
  quintOut: 'var(--tz-ease-quint-out)',
};
export const font = {
  body: {
    fontFamily: 'var(--tz-font-body-font-family)',
    fontVariationSettings: 'var(--tz-font-body-font-variation-settings)',
    fontWeight: 'var(--tz-font-body-font-weight)',
    fontSize: 'var(--tz-font-body-font-size)',
    letterSpacing: 'var(--tz-font-body-letter-spacing)',
    lineHeight: 'var(--tz-font-body-line-height)',
  },
  bodyLongform: {
    fontFamily: 'var(--tz-font-body-longform-font-family)',
    fontVariationSettings: 'var(--tz-font-body-longform-font-variation-settings)',
    fontWeight: 'var(--tz-font-body-longform-font-weight)',
    fontSize: 'var(--tz-font-body-longform-font-size)',
    letterSpacing: 'var(--tz-font-body-longform-letter-spacing)',
    lineHeight: 'var(--tz-font-body-longform-line-height)',
  },
  bodyStrong: {
    fontFamily: 'var(--tz-font-body-strong-font-family)',
    fontVariationSettings: 'var(--tz-font-body-strong-font-variation-settings)',
    fontWeight: 'var(--tz-font-body-strong-font-weight)',
    fontSize: 'var(--tz-font-body-strong-font-size)',
    letterSpacing: 'var(--tz-font-body-strong-letter-spacing)',
    lineHeight: 'var(--tz-font-body-strong-line-height)',
  },
  heading1: {
    fontFamily: 'var(--tz-font-heading1-font-family)',
    fontVariationSettings: 'var(--tz-font-heading1-font-variation-settings)',
    fontWeight: 'var(--tz-font-heading1-font-weight)',
    fontSize: 'var(--tz-font-heading1-font-size)',
    lineHeight: 'var(--tz-font-heading1-line-height)',
    letterSpacing: 'var(--tz-font-heading1-letter-spacing)',
  },
  heading2: {
    fontFamily: 'var(--tz-font-heading2-font-family)',
    fontVariationSettings: 'var(--tz-font-heading2-font-variation-settings)',
    fontWeight: 'var(--tz-font-heading2-font-weight)',
    fontSize: 'var(--tz-font-heading2-font-size)',
    lineHeight: 'var(--tz-font-heading2-line-height)',
    letterSpacing: 'var(--tz-font-heading2-letter-spacing)',
  },
  heading3: {
    fontFamily: 'var(--tz-font-heading3-font-family)',
    fontVariationSettings: 'var(--tz-font-heading3-font-variation-settings)',
    fontWeight: 'var(--tz-font-heading3-font-weight)',
    fontSize: 'var(--tz-font-heading3-font-size)',
    lineHeight: 'var(--tz-font-heading3-line-height)',
    letterSpacing: 'var(--tz-font-heading3-letter-spacing)',
  },
  heading4: {
    fontFamily: 'var(--tz-font-heading4-font-family)',
    fontVariationSettings: 'var(--tz-font-heading4-font-variation-settings)',
    fontWeight: 'var(--tz-font-heading4-font-weight)',
    fontSize: 'var(--tz-font-heading4-font-size)',
    letterSpacing: 'var(--tz-font-heading4-letter-spacing)',
    lineHeight: 'var(--tz-font-heading4-line-height)',
  },
  heading5: {
    fontFamily: 'var(--tz-font-heading5-font-family)',
    fontVariationSettings: 'var(--tz-font-heading5-font-variation-settings)',
    fontWeight: 'var(--tz-font-heading5-font-weight)',
    fontSize: 'var(--tz-font-heading5-font-size)',
    letterSpacing: 'var(--tz-font-heading5-letter-spacing)',
    lineHeight: 'var(--tz-font-heading5-line-height)',
  },
  heading6: {
    fontFamily: 'var(--tz-font-heading6-font-family)',
    fontVariationSettings: 'var(--tz-font-heading6-font-variation-settings)',
    fontWeight: 'var(--tz-font-heading6-font-weight)',
    fontSize: 'var(--tz-font-heading6-font-size)',
    letterSpacing: 'var(--tz-font-heading6-letter-spacing)',
    lineHeight: 'var(--tz-font-heading6-line-height)',
  },
  labelSmall: {
    fontFamily: 'var(--tz-font-label-small-font-family)',
    fontVariationSettings: 'var(--tz-font-label-small-font-variation-settings)',
    fontWeight: 'var(--tz-font-label-small-font-weight)',
    fontSize: 'var(--tz-font-label-small-font-size)',
    lineHeight: 'var(--tz-font-label-small-line-height)',
    letterSpacing: 'var(--tz-font-label-small-letter-spacing)',
  },
  mono: 'var(--tz-font-mono)',
  sans: 'var(--tz-font-sans)',
};
export const layer = {
  base: 'var(--tz-layer-base)',
  menu: 'var(--tz-layer-menu)',
  modal: 'var(--tz-layer-modal)',
  nav: 'var(--tz-layer-nav)',
  popover: 'var(--tz-layer-popover)',
  tooltip: 'var(--tz-layer-tooltip)',
};
export const radius = {
  100: 'var(--tz-radius-100)',
  200: 'var(--tz-radius-200)',
  300: 'var(--tz-radius-300)',
  400: 'var(--tz-radius-400)',
  500: 'var(--tz-radius-500)',
  1000: 'var(--tz-radius-1000)',
  '000': 'var(--tz-radius-000)',
};
export const shadow = {
  100: 'var(--tz-shadow-100)',
  300: 'var(--tz-shadow-300)',
};
export const space = {
  100: 'var(--tz-space-100)',
  200: 'var(--tz-space-200)',
  300: 'var(--tz-space-300)',
  400: 'var(--tz-space-400)',
  500: 'var(--tz-space-500)',
  600: 'var(--tz-space-600)',
  700: 'var(--tz-space-700)',
  800: 'var(--tz-space-800)',
  900: 'var(--tz-space-900)',
  '000': 'var(--tz-space-000)',
  controlL: 'var(--tz-space-control-l)',
  controlM: 'var(--tz-space-control-m)',
  controlS: 'var(--tz-space-control-s)',
};
export const timing = {
  default: 'var(--tz-timing-default)',
  deliberate: 'var(--tz-timing-deliberate)',
  moderate: 'var(--tz-timing-moderate)',
  quick: 'var(--tz-timing-quick)',
  slow: 'var(--tz-timing-slow)',
};
