/**
 * Design Tokens
 * Autogenerated from tokens.json.
 * DO NOT EDIT!
 */

import {
  ColorToken,
  DimensionToken,
  FontToken,
  ParsedColorToken,
  ParsedDimensionToken,
  ParsedFontToken,
} from '@cobalt-ui/core';

export declare const tokens: {
  'color.black': ColorToken['$value'];
  'color.blueLighter': ColorToken['$value'];
  'color.blueLight': ColorToken['$value'];
  'color.blue': ColorToken['$value'];
  'color.blueDark': ColorToken['$value'];
  'color.blueDarker': ColorToken['$value'];
  'color.blueText': ColorToken['$value'];
  'color.greenLighter': ColorToken['$value'];
  'color.greenLight': ColorToken['$value'];
  'color.green': ColorToken['$value'];
  'color.greenDark': ColorToken['$value'];
  'color.greenDarker': ColorToken['$value'];
  'color.greenText': ColorToken['$value'];
  'color.indigoLighter': ColorToken['$value'];
  'color.indigoLight': ColorToken['$value'];
  'color.indigo': ColorToken['$value'];
  'color.indigoDark': ColorToken['$value'];
  'color.indigoDarker': ColorToken['$value'];
  'color.indigoText': ColorToken['$value'];
  'color.inkLightest': ColorToken['$value'];
  'color.inkLighter': ColorToken['$value'];
  'color.inkLight': ColorToken['$value'];
  'color.ink': ColorToken['$value'];
  'color.orangeLighter': ColorToken['$value'];
  'color.orangeLight': ColorToken['$value'];
  'color.orange': ColorToken['$value'];
  'color.orangeDark': ColorToken['$value'];
  'color.orangeDarker': ColorToken['$value'];
  'color.orangeText': ColorToken['$value'];
  'color.purpleLighter': ColorToken['$value'];
  'color.purpleLight': ColorToken['$value'];
  'color.purple': ColorToken['$value'];
  'color.purpleDark': ColorToken['$value'];
  'color.purpleDarker': ColorToken['$value'];
  'color.purpleText': ColorToken['$value'];
  'color.redLighter': ColorToken['$value'];
  'color.redLight': ColorToken['$value'];
  'color.red': ColorToken['$value'];
  'color.redDark': ColorToken['$value'];
  'color.redDarker': ColorToken['$value'];
  'color.redText': ColorToken['$value'];
  'color.skyLighter': ColorToken['$value'];
  'color.skyLight': ColorToken['$value'];
  'color.sky': ColorToken['$value'];
  'color.skyDark': ColorToken['$value'];
  'color.tealLighter': ColorToken['$value'];
  'color.tealLight': ColorToken['$value'];
  'color.teal': ColorToken['$value'];
  'color.tealDark': ColorToken['$value'];
  'color.tealDarker': ColorToken['$value'];
  'color.tealText': ColorToken['$value'];
  'color.white': ColorToken['$value'];
  'color.yellowLighter': ColorToken['$value'];
  'color.yellowLight': ColorToken['$value'];
  'color.yellow': ColorToken['$value'];
  'color.yellowDark': ColorToken['$value'];
  'color.yellowDarker': ColorToken['$value'];
  'color.yellowText': ColorToken['$value'];
  'font.family.base': FontToken['$value'];
  'font.family.mono': FontToken['$value'];
  'space.none': DimensionToken['$value'];
  'space.extraTight': DimensionToken['$value'];
  'space.tight': DimensionToken['$value'];
  'space.baseTight': DimensionToken['$value'];
  'space.base': DimensionToken['$value'];
  'space.loose': DimensionToken['$value'];
  'space.extraLoose': DimensionToken['$value'];
};

export declare const meta: {
  'color.black': ParsedColorToken;
  'color.blueLighter': ParsedColorToken;
  'color.blueLight': ParsedColorToken;
  'color.blue': ParsedColorToken;
  'color.blueDark': ParsedColorToken;
  'color.blueDarker': ParsedColorToken;
  'color.blueText': ParsedColorToken;
  'color.greenLighter': ParsedColorToken;
  'color.greenLight': ParsedColorToken;
  'color.green': ParsedColorToken;
  'color.greenDark': ParsedColorToken;
  'color.greenDarker': ParsedColorToken;
  'color.greenText': ParsedColorToken;
  'color.indigoLighter': ParsedColorToken;
  'color.indigoLight': ParsedColorToken;
  'color.indigo': ParsedColorToken;
  'color.indigoDark': ParsedColorToken;
  'color.indigoDarker': ParsedColorToken;
  'color.indigoText': ParsedColorToken;
  'color.inkLightest': ParsedColorToken;
  'color.inkLighter': ParsedColorToken;
  'color.inkLight': ParsedColorToken;
  'color.ink': ParsedColorToken;
  'color.orangeLighter': ParsedColorToken;
  'color.orangeLight': ParsedColorToken;
  'color.orange': ParsedColorToken;
  'color.orangeDark': ParsedColorToken;
  'color.orangeDarker': ParsedColorToken;
  'color.orangeText': ParsedColorToken;
  'color.purpleLighter': ParsedColorToken;
  'color.purpleLight': ParsedColorToken;
  'color.purple': ParsedColorToken;
  'color.purpleDark': ParsedColorToken;
  'color.purpleDarker': ParsedColorToken;
  'color.purpleText': ParsedColorToken;
  'color.redLighter': ParsedColorToken;
  'color.redLight': ParsedColorToken;
  'color.red': ParsedColorToken;
  'color.redDark': ParsedColorToken;
  'color.redDarker': ParsedColorToken;
  'color.redText': ParsedColorToken;
  'color.skyLighter': ParsedColorToken;
  'color.skyLight': ParsedColorToken;
  'color.sky': ParsedColorToken;
  'color.skyDark': ParsedColorToken;
  'color.tealLighter': ParsedColorToken;
  'color.tealLight': ParsedColorToken;
  'color.teal': ParsedColorToken;
  'color.tealDark': ParsedColorToken;
  'color.tealDarker': ParsedColorToken;
  'color.tealText': ParsedColorToken;
  'color.white': ParsedColorToken;
  'color.yellowLighter': ParsedColorToken;
  'color.yellowLight': ParsedColorToken;
  'color.yellow': ParsedColorToken;
  'color.yellowDark': ParsedColorToken;
  'color.yellowDarker': ParsedColorToken;
  'color.yellowText': ParsedColorToken;
  'font.family.base': ParsedFontToken;
  'font.family.mono': ParsedFontToken;
  'space.none': ParsedDimensionToken;
  'space.extraTight': ParsedDimensionToken;
  'space.tight': ParsedDimensionToken;
  'space.baseTight': ParsedDimensionToken;
  'space.base': ParsedDimensionToken;
  'space.loose': ParsedDimensionToken;
  'space.extraLoose': ParsedDimensionToken;
};

export declare const modes: Record<string, never>;

export declare function token(tokenID: keyof typeof tokens, modeName: never): typeof tokens[typeof tokenID];
export declare function token(tokenID: keyof typeof modes, modeName: keyof typeof modes[typeof tokenID]): typeof modes[typeof tokenID];
