/**
 * Design Tokens
 * Autogenerated from tokens.json.
 * DO NOT EDIT!
 */

import {
  ColorToken,
  FontToken,
  DimensionToken,
  DurationToken,
  CubicBezierToken,
  LinkToken,
  StrokeStyleToken,
  BorderToken,
  TransitionToken,
  ShadowToken,
  GradientToken,
  TypographyToken,
} from '@cobalt-ui/core';

export declare const tokens: {
  'color.black': ColorToken['$value'];
  'color.blueLighter': ColorToken['$value'];
  'color.blueLight': ColorToken['$value'];
  'color.blue': ColorToken['$value'];
  'color.blueDark': ColorToken['$value'];
  'color.blueDarker': ColorToken['$value'];
  'color.blueText': ColorToken['$value'];
  'color.greenLighter': ColorToken['$value'];
  'color.greenLight': ColorToken['$value'];
  'color.green': ColorToken['$value'];
  'color.greenDark': ColorToken['$value'];
  'color.greenDarker': ColorToken['$value'];
  'color.greenText': ColorToken['$value'];
  'color.indigoLighter': ColorToken['$value'];
  'color.indigoLight': ColorToken['$value'];
  'color.indigo': ColorToken['$value'];
  'color.indigoDark': ColorToken['$value'];
  'color.indigoDarker': ColorToken['$value'];
  'color.indigoText': ColorToken['$value'];
  'color.inkLightest': ColorToken['$value'];
  'color.inkLighter': ColorToken['$value'];
  'color.inkLight': ColorToken['$value'];
  'color.ink': ColorToken['$value'];
  'color.orangeLighter': ColorToken['$value'];
  'color.orangeLight': ColorToken['$value'];
  'color.orange': ColorToken['$value'];
  'color.orangeDark': ColorToken['$value'];
  'color.orangeDarker': ColorToken['$value'];
  'color.orangeText': ColorToken['$value'];
  'color.purpleLighter': ColorToken['$value'];
  'color.purpleLight': ColorToken['$value'];
  'color.purple': ColorToken['$value'];
  'color.purpleDark': ColorToken['$value'];
  'color.purpleDarker': ColorToken['$value'];
  'color.purpleText': ColorToken['$value'];
  'color.redLighter': ColorToken['$value'];
  'color.redLight': ColorToken['$value'];
  'color.red': ColorToken['$value'];
  'color.redDark': ColorToken['$value'];
  'color.redDarker': ColorToken['$value'];
  'color.redText': ColorToken['$value'];
  'color.skyLighter': ColorToken['$value'];
  'color.skyLight': ColorToken['$value'];
  'color.sky': ColorToken['$value'];
  'color.skyDark': ColorToken['$value'];
  'color.tealLighter': ColorToken['$value'];
  'color.tealLight': ColorToken['$value'];
  'color.teal': ColorToken['$value'];
  'color.tealDark': ColorToken['$value'];
  'color.tealDarker': ColorToken['$value'];
  'color.tealText': ColorToken['$value'];
  'color.white': ColorToken['$value'];
  'color.yellowLighter': ColorToken['$value'];
  'color.yellowLight': ColorToken['$value'];
  'color.yellow': ColorToken['$value'];
  'color.yellowDark': ColorToken['$value'];
  'color.yellowDarker': ColorToken['$value'];
  'color.yellowText': ColorToken['$value'];
  'font.family.base': FontToken['$value'];
  'font.family.mono': FontToken['$value'];
  'space.none': DimensionToken['$value'];
  'space.extraTight': DimensionToken['$value'];
  'space.tight': DimensionToken['$value'];
  'space.baseTight': DimensionToken['$value'];
  'space.base': DimensionToken['$value'];
  'space.loose': DimensionToken['$value'];
  'space.extraLoose': DimensionToken['$value'];
};

export declare const meta: {
  'color.black': ColorToken;
  'color.blueLighter': ColorToken;
  'color.blueLight': ColorToken;
  'color.blue': ColorToken;
  'color.blueDark': ColorToken;
  'color.blueDarker': ColorToken;
  'color.blueText': ColorToken;
  'color.greenLighter': ColorToken;
  'color.greenLight': ColorToken;
  'color.green': ColorToken;
  'color.greenDark': ColorToken;
  'color.greenDarker': ColorToken;
  'color.greenText': ColorToken;
  'color.indigoLighter': ColorToken;
  'color.indigoLight': ColorToken;
  'color.indigo': ColorToken;
  'color.indigoDark': ColorToken;
  'color.indigoDarker': ColorToken;
  'color.indigoText': ColorToken;
  'color.inkLightest': ColorToken;
  'color.inkLighter': ColorToken;
  'color.inkLight': ColorToken;
  'color.ink': ColorToken;
  'color.orangeLighter': ColorToken;
  'color.orangeLight': ColorToken;
  'color.orange': ColorToken;
  'color.orangeDark': ColorToken;
  'color.orangeDarker': ColorToken;
  'color.orangeText': ColorToken;
  'color.purpleLighter': ColorToken;
  'color.purpleLight': ColorToken;
  'color.purple': ColorToken;
  'color.purpleDark': ColorToken;
  'color.purpleDarker': ColorToken;
  'color.purpleText': ColorToken;
  'color.redLighter': ColorToken;
  'color.redLight': ColorToken;
  'color.red': ColorToken;
  'color.redDark': ColorToken;
  'color.redDarker': ColorToken;
  'color.redText': ColorToken;
  'color.skyLighter': ColorToken;
  'color.skyLight': ColorToken;
  'color.sky': ColorToken;
  'color.skyDark': ColorToken;
  'color.tealLighter': ColorToken;
  'color.tealLight': ColorToken;
  'color.teal': ColorToken;
  'color.tealDark': ColorToken;
  'color.tealDarker': ColorToken;
  'color.tealText': ColorToken;
  'color.white': ColorToken;
  'color.yellowLighter': ColorToken;
  'color.yellowLight': ColorToken;
  'color.yellow': ColorToken;
  'color.yellowDark': ColorToken;
  'color.yellowDarker': ColorToken;
  'color.yellowText': ColorToken;
  'font.family.base': FontToken;
  'font.family.mono': FontToken;
  'space.none': DimensionToken;
  'space.extraTight': DimensionToken;
  'space.tight': DimensionToken;
  'space.baseTight': DimensionToken;
  'space.base': DimensionToken;
  'space.loose': DimensionToken;
  'space.extraLoose': DimensionToken;
};

export declare const modes: Record<string, never>;

export declare function token(tokenID: keyof typeof tokens, modeName?: undefined): typeof tokens[typeof tokenID];
export declare function token(tokenID: keyof typeof modes, modeName?: keyof typeof modes[typeof tokenID]): typeof modes[typeof tokenID];
