/**
 * Design Tokens
 * Autogenerated from tokens.json.
 * DO NOT EDIT!
 */

export const tokens = {
  'color.blue400': '#2680eb',
  'color.blue500': '#1473e6',
  'color.blue600': '#0d66d0',
  'color.blue700': '#095aba',
  'color.gray50': '#ffffff',
  'color.gray75': '#fafafa',
  'color.gray100': '#f5f5f5',
  'color.gray200': '#eaeaea',
  'color.gray300': '#e1e1e1',
  'color.gray400': '#cacaca',
  'color.gray500': '#b3b3b3',
  'color.gray600': '#8e8e8e',
  'color.gray700': '#6e6e6e',
  'color.gray800': '#4b4b4b',
  'color.gray900': '#2c2c2c',
  'color.green400': '#2d9d78',
  'color.green500': '#268e6c',
  'color.green600': '#12805c',
  'color.green700': '#107154',
  'color.red400': '#e34850',
  'color.red500': '#d7373f',
  'color.red600': '#c9252d',
  'color.red700': '#bb121a',
  'color.orange400': '#e68619',
  'color.orange500': '#da7b11',
  'color.orange600': '#cb6f10',
  'color.orange700': '#bd640d',
  'color.label.celery400': '#44b556',
  'color.label.celery500': '#3da74e',
  'color.label.celery600': '#3da74e',
  'color.label.celery700': '#3da74e',
  'color.label.chartreuse400': '#85d044',
  'color.label.chartreuse500': '#7cc33f',
  'color.label.chartreuse600': '#73b53a',
  'color.label.chartreuse700': '#6aa834',
  'color.label.fuchsia400': '#c038cc',
  'color.label.fuchsia500': '#b130bd',
  'color.label.fuchsia600': '#a228ad',
  'color.label.fuchsia700': '#93219e',
  'color.label.indigo400': '#6767ec',
  'color.label.indigo500': '#5c5ce0',
  'color.label.indigo600': '#5151d3',
  'color.label.indigo700': '#4646c6',
  'color.label.magenta400': '#d83790',
  'color.label.magenta500': '#ce2783',
  'color.label.magenta600': '#bc1c74',
  'color.label.magenta700': '#ae0e66',
  'color.label.purple400': '#9256d9',
  'color.label.purple500': '#864ccc',
  'color.label.purple600': '#7a42bf',
  'color.label.purple700': '#6f38b1',
  'color.label.seafoam400': '#1b959a',
  'color.label.seafoam500': '#16878c',
  'color.label.seafoam600': '#0f797d',
  'color.label.seafoam700': '#096c6f',
  'color.label.yellow400': '#dfbf00',
  'color.label.yellow500': '#d2b200',
  'color.label.yellow600': '#c4a600',
  'color.label.yellow700': '#b79900',
  'font.family.clean': ['Adobe Clean'],
  'font.family.cleanSerif': ['Adobe Clean Serif'],
  'font.family.cleanHan': ['Adobe Clean Han'],
  'font.family.sourceCode': ['Source Code Pro'],
  'font.size.50': '11px',
  'font.size.75': '12px',
  'font.size.100': '14px',
  'font.size.200': '16px',
  'font.size.300': '18px',
  'font.size.400': '20px',
  'font.size.500': '22px',
  'font.size.600': '25px',
  'font.size.700': '28px',
  'font.size.800': '32px',
  'font.size.900': '36px',
  'font.size.1000': '40px',
  'font.size.1100': '45px',
  'font.size.1200': '50px',
  'font.size.1300': '60px',
};

export const meta = {
  'color.blue400': {
    '$value': '#2680eb',
    '$extensions': {
      mode: {
        lightest: '#378ef0',
        light: '#2680eb',
        dark: '#2680eb',
        darkest: '#1473e6',
      },
    },
  },
  'color.blue500': {
    '$value': '#1473e6',
    '$extensions': {
      mode: {
        lightest: '#2680eb',
        light: '#1473e6',
        dark: '#378ef0',
        darkest: '#2680eb',
      },
    },
  },
  'color.blue600': {
    '$value': '#0d66d0',
    '$extensions': {
      mode: {
        lightest: '#1473e6',
        light: '#0d66d0',
        dark: '#4b9cf5',
        darkest: '#378ef0',
      },
    },
  },
  'color.blue700': {
    '$value': '#095aba',
    '$extensions': {
      mode: {
        lightest: '#0d66d0',
        light: '#095aba',
        dark: '#5aa9fa',
        darkest: '#4b9cf5',
      },
    },
  },
  'color.gray50': {
    '$value': '#ffffff',
    '$extensions': {
      mode: {
        lightest: '#ffffff',
        light: '#ffffff',
        dark: '#252525',
        darkest: '#080808',
      },
    },
  },
  'color.gray75': {
    '$value': '#fafafa',
    '$extensions': {
      mode: {
        lightest: '#ffffff',
        light: '#fafafa',
        dark: '#2f2f2f',
        darkest: '#1a1a1a',
      },
    },
  },
  'color.gray100': {
    '$value': '#f5f5f5',
    '$extensions': {
      mode: {
        lightest: '#ffffff',
        light: '#f5f5f5',
        dark: '#323232',
        darkest: '#1e1e1e',
      },
    },
  },
  'color.gray200': {
    '$value': '#eaeaea',
    '$extensions': {
      mode: {
        lightest: '#f4f4f4',
        light: '#eaeaea',
        dark: '#3e3e3e',
        darkest: '#2c2c2c',
      },
    },
  },
  'color.gray300': {
    '$value': '#e1e1e1',
    '$extensions': {
      mode: {
        lightest: '#eaeaea',
        light: '#e1e1e1',
        dark: '#4a4a4a',
        darkest: '#393939',
      },
    },
  },
  'color.gray400': {
    '$value': '#cacaca',
    '$extensions': {
      mode: {
        lightest: '#d3d3d3',
        light: '#cacaca',
        dark: '#5a5a5a',
        darkest: '#494949',
      },
    },
  },
  'color.gray500': {
    '$value': '#b3b3b3',
    '$extensions': {
      mode: {
        lightest: '#bcbcbc',
        light: '#b3b3b3',
        dark: '#6e6e6e',
        darkest: '#5c5c5c',
      },
    },
  },
  'color.gray600': {
    '$value': '#8e8e8e',
    '$extensions': {
      mode: {
        lightest: '#959595',
        light: '#8e8e8e',
        dark: '#909090',
        darkest: '#7c7c7c',
      },
    },
  },
  'color.gray700': {
    '$value': '#6e6e6e',
    '$extensions': {
      mode: {
        lightest: '#747474',
        light: '#6e6e6e',
        dark: '#b9b9b9',
        darkest: '#a2a2a2',
      },
    },
  },
  'color.gray800': {
    '$value': '#4b4b4b',
    '$extensions': {
      mode: {
        lightest: '#505050',
        light: '#4b4b4b',
        dark: '#e3e3e3',
        darkest: '#c8c8c8',
      },
    },
  },
  'color.gray900': {
    '$value': '#2c2c2c',
    '$extensions': {
      mode: {
        lightest: '#323232',
        light: '#2c2c2c',
        dark: '#ffffff',
        darkest: '#efefef',
      },
    },
  },
  'color.green400': {
    '$value': '#2d9d78',
    '$extensions': {
      mode: {
        lightest: '#33ab84',
        light: '#2d9d78',
        dark: '#2d9d78',
        darkest: '#268e6c',
      },
    },
  },
  'color.green500': {
    '$value': '#268e6c',
    '$extensions': {
      mode: {
        lightest: '#2d9d78',
        light: '#268e6c',
        dark: '#33ab84',
        darkest: '#2d9d78',
      },
    },
  },
  'color.green600': {
    '$value': '#12805c',
    '$extensions': {
      mode: {
        lightest: '#268e6c',
        light: '#12805c',
        dark: '#39b990',
        darkest: '#33ab84',
      },
    },
  },
  'color.green700': {
    '$value': '#107154',
    '$extensions': {
      mode: {
        lightest: '#12805c',
        light: '#107154',
        dark: '#3fc89c',
        darkest: '#39b990',
      },
    },
  },
  'color.red400': {
    '$value': '#e34850',
    '$extensions': {
      mode: {
        lightest: '#ec5b62',
        light: '#e34850',
        dark: '#e34850',
        darkest: '#d7373f',
      },
    },
  },
  'color.red500': {
    '$value': '#d7373f',
    '$extensions': {
      mode: {
        lightest: '#e34850',
        light: '#d7373f',
        dark: '#ec5b62',
        darkest: '#e34850',
      },
    },
  },
  'color.red600': {
    '$value': '#c9252d',
    '$extensions': {
      mode: {
        lightest: '#d7373f',
        light: '#c9252d',
        dark: '#f76d74',
        darkest: '#ec5b62',
      },
    },
  },
  'color.red700': {
    '$value': '#bb121a',
    '$extensions': {
      mode: {
        lightest: '#c9252d',
        light: '#bb121a',
        dark: '#ff7b82',
        darkest: '#f76d74',
      },
    },
  },
  'color.orange400': {
    '$value': '#e68619',
    '$extensions': {
      mode: {
        lightest: '#f29423',
        light: '#e68619',
        dark: '#e68619',
        darkest: '#da7b11',
      },
    },
  },
  'color.orange500': {
    '$value': '#da7b11',
    '$extensions': {
      mode: {
        lightest: '#e68619',
        light: '#da7b11',
        dark: '#f29423',
        darkest: '#e68619',
      },
    },
  },
  'color.orange600': {
    '$value': '#cb6f10',
    '$extensions': {
      mode: {
        lightest: '#da7b11',
        light: '#cb6f10',
        dark: '#f9a43f',
        darkest: '#f29423',
      },
    },
  },
  'color.orange700': {
    '$value': '#bd640d',
    '$extensions': {
      mode: {
        lightest: '#cb6f10',
        light: '#bd640d',
        dark: '#ffb55b',
        darkest: '#f9a43f',
      },
    },
  },
  'color.label.celery400': {
    '$value': '#44b556',
    '$extensions': {
      mode: {
        lightest: '#4bc35f',
        light: '#44b556',
        dark: '#44b556',
        darkest: '#3da74e',
      },
    },
  },
  'color.label.celery500': {
    '$value': '#3da74e',
    '$extensions': {
      mode: {
        lightest: '#44b556',
        light: '#3da74e',
        dark: '#4bc35f',
        darkest: '#44b556',
      },
    },
  },
  'color.label.celery600': {
    '$value': '#3da74e',
    '$extensions': {
      mode: {
        lightest: '#3da74e',
        light: '#3da74e',
        dark: '#51d267',
        darkest: '#4bc35f',
      },
    },
  },
  'color.label.celery700': {
    '$value': '#3da74e',
    '$extensions': {
      mode: {
        lightest: '#379947',
        light: '#3da74e',
        dark: '#58e06f',
        darkest: '#51d267',
      },
    },
  },
  'color.label.chartreuse400': {
    '$value': '#85d044',
    '$extensions': {
      mode: {
        lightest: '#8ede49',
        light: '#85d044',
        dark: '#85d044',
        darkest: '#7cc33f',
      },
    },
  },
  'color.label.chartreuse500': {
    '$value': '#7cc33f',
    '$extensions': {
      mode: {
        lightest: '#85d044',
        light: '#7cc33f',
        dark: '#8ede49',
        darkest: '#85d044',
      },
    },
  },
  'color.label.chartreuse600': {
    '$value': '#73b53a',
    '$extensions': {
      mode: {
        lightest: '#7cc33f',
        light: '#73b53a',
        dark: '#9bec54',
        darkest: '#8ede49',
      },
    },
  },
  'color.label.chartreuse700': {
    '$value': '#6aa834',
    '$extensions': {
      mode: {
        lightest: '#73b53a',
        light: '#6aa834',
        dark: '#a3f858',
        darkest: '#9bec54',
      },
    },
  },
  'color.label.fuchsia400': {
    '$value': '#c038cc',
    '$extensions': {
      mode: {
        lightest: '#cf3edc',
        light: '#c038cc',
        dark: '#c038cc',
        darkest: '#b130bd',
      },
    },
  },
  'color.label.fuchsia500': {
    '$value': '#b130bd',
    '$extensions': {
      mode: {
        lightest: '#c038cc',
        light: '#b130bd',
        dark: '#cf3edc',
        darkest: '#c038cc',
      },
    },
  },
  'color.label.fuchsia600': {
    '$value': '#a228ad',
    '$extensions': {
      mode: {
        lightest: '#b130bd',
        light: '#a228ad',
        dark: '#d951e5',
        darkest: '#cf3edc',
      },
    },
  },
  'color.label.fuchsia700': {
    '$value': '#93219e',
    '$extensions': {
      mode: {
        lightest: '#a228ad',
        light: '#93219e',
        dark: '#e366ef',
        darkest: '#d951e5',
      },
    },
  },
  'color.label.indigo400': {
    '$value': '#6767ec',
    '$extensions': {
      mode: {
        lightest: '#7575f1',
        light: '#6767ec',
        dark: '#6767ec',
        darkest: '#5c5ce0',
      },
    },
  },
  'color.label.indigo500': {
    '$value': '#5c5ce0',
    '$extensions': {
      mode: {
        lightest: '#6767ec',
        light: '#5c5ce0',
        dark: '#7575f1',
        darkest: '#6767ec',
      },
    },
  },
  'color.label.indigo600': {
    '$value': '#5151d3',
    '$extensions': {
      mode: {
        lightest: '#5c5ce0',
        light: '#5151d3',
        dark: '#8282f6',
        darkest: '#7575f1',
      },
    },
  },
  'color.label.indigo700': {
    '$value': '#4646c6',
    '$extensions': {
      mode: {
        lightest: '#5151d3',
        light: '#4646c6',
        dark: '#9090fa',
        darkest: '#8282f6',
      },
    },
  },
  'color.label.magenta400': {
    '$value': '#d83790',
    '$extensions': {
      mode: {
        lightest: '#e2499d',
        light: '#d83790',
        dark: '#d83790',
        darkest: '#ca2996',
      },
    },
  },
  'color.label.magenta500': {
    '$value': '#ce2783',
    '$extensions': {
      mode: {
        lightest: '#d83790',
        light: '#ce2783',
        dark: '#e2499d',
        darkest: '#d83790',
      },
    },
  },
  'color.label.magenta600': {
    '$value': '#bc1c74',
    '$extensions': {
      mode: {
        lightest: '#ca2982',
        light: '#bc1c74',
        dark: '#ec5aaa',
        darkest: '#e2499d',
      },
    },
  },
  'color.label.magenta700': {
    '$value': '#ae0e66',
    '$extensions': {
      mode: {
        lightest: '#bc1c74',
        light: '#ae0e66',
        dark: '#f56bb7',
        darkest: '#ec5aaa',
      },
    },
  },
  'color.label.purple400': {
    '$value': '#9256d9',
    '$extensions': {
      mode: {
        lightest: '#9d64e1',
        light: '#9256d9',
        dark: '#9256d9',
        darkest: '#864ccc',
      },
    },
  },
  'color.label.purple500': {
    '$value': '#864ccc',
    '$extensions': {
      mode: {
        lightest: '#9256d9',
        light: '#864ccc',
        dark: '#9d64e1',
        darkest: '#9256d9',
      },
    },
  },
  'color.label.purple600': {
    '$value': '#7a42bf',
    '$extensions': {
      mode: {
        lightest: '#864ccc',
        light: '#7a42bf',
        dark: '#a873e9',
        darkest: '#9d64e1',
      },
    },
  },
  'color.label.purple700': {
    '$value': '#6f38b1',
    '$extensions': {
      mode: {
        lightest: '#7a42bf',
        light: '#6f38b1',
        dark: '#b483f0',
        darkest: '#a873df',
      },
    },
  },
  'color.label.seafoam400': {
    '$value': '#1b959a',
    '$extensions': {
      mode: {
        lightest: '#20a3a8',
        light: '#1b959a',
        dark: '#1b959a',
        darkest: '#16878c',
      },
    },
  },
  'color.label.seafoam500': {
    '$value': '#16878c',
    '$extensions': {
      mode: {
        lightest: '#1b959a',
        light: '#16878c',
        dark: '#20a3a8',
        darkest: '#1b959a',
      },
    },
  },
  'color.label.seafoam600': {
    '$value': '#0f797d',
    '$extensions': {
      mode: {
        lightest: '#16878c',
        light: '#0f797d',
        dark: '#23b2b8',
        darkest: '#20a3a8',
      },
    },
  },
  'color.label.seafoam700': {
    '$value': '#096c6f',
    '$extensions': {
      mode: {
        lightest: '#0f797d',
        light: '#096c6f',
        dark: '#26c0c7',
        darkest: '#23b2b8',
      },
    },
  },
  'color.label.yellow400': {
    '$value': '#dfbf00',
    '$extensions': {
      mode: {
        lightest: '#edcc00',
        light: '#dfbf00',
        dark: '#dfbf00',
        darkest: '#d2b200',
      },
    },
  },
  'color.label.yellow500': {
    '$value': '#d2b200',
    '$extensions': {
      mode: {
        lightest: '#dfbf00',
        light: '#d2b200',
        dark: '#edcc00',
        darkest: '#dfbf00',
      },
    },
  },
  'color.label.yellow600': {
    '$value': '#c4a600',
    '$extensions': {
      mode: {
        lightest: '#d2b200',
        light: '#c4a600',
        dark: '#fad900',
        darkest: '#edcc00',
      },
    },
  },
  'color.label.yellow700': {
    '$value': '#b79900',
    '$extensions': {
      mode: {
        lightest: '#c4a600',
        light: '#b79900',
        dark: '#ffe22e',
        darkest: '#fad900',
      },
    },
  },
  'font.family.clean': {
    '$value': 'Adobe Clean',
  },
  'font.family.cleanSerif': {
    '$value': 'Adobe Clean Serif',
  },
  'font.family.cleanHan': {
    '$value': 'Adobe Clean Han',
  },
  'font.family.sourceCode': {
    '$value': 'Source Code Pro',
  },
  'font.size.50': {
    '$value': '11px',
    '$extensions': {
      mode: {
        desktop: '11px',
        mobile: '13px',
      },
    },
  },
  'font.size.75': {
    '$value': '12px',
    '$extensions': {
      mode: {
        desktop: '12px',
        mobile: '13px',
      },
    },
  },
  'font.size.100': {
    '$value': '14px',
    '$extensions': {
      mode: {
        desktop: '14px',
        mobile: '17px',
      },
    },
  },
  'font.size.200': {
    '$value': '16px',
    '$extensions': {
      mode: {
        desktop: '16px',
        mobile: '19px',
      },
    },
  },
  'font.size.300': {
    '$value': '18px',
    '$extensions': {
      mode: {
        desktop: '18px',
        mobile: '22px',
      },
    },
  },
  'font.size.400': {
    '$value': '20px',
    '$extensions': {
      mode: {
        desktop: '20px',
        mobile: '24px',
      },
    },
  },
  'font.size.500': {
    '$value': '22px',
    '$extensions': {
      mode: {
        desktop: '22px',
        mobile: '27px',
      },
    },
  },
  'font.size.600': {
    '$value': '25px',
    '$extensions': {
      mode: {
        desktop: '25px',
        mobile: '31px',
      },
    },
  },
  'font.size.700': {
    '$value': '28px',
    '$extensions': {
      mode: {
        desktop: '28px',
        mobile: '34px',
      },
    },
  },
  'font.size.800': {
    '$value': '32px',
    '$extensions': {
      mode: {
        desktop: '32px',
        mobile: '39px',
      },
    },
  },
  'font.size.900': {
    '$value': '36px',
    '$extensions': {
      mode: {
        desktop: '36px',
        mobile: '44px',
      },
    },
  },
  'font.size.1000': {
    '$value': '40px',
    '$extensions': {
      mode: {
        desktop: '40px',
        mobile: '49px',
      },
    },
  },
  'font.size.1100': {
    '$value': '45px',
    '$extensions': {
      mode: {
        desktop: '45px',
        mobile: '55px',
      },
    },
  },
  'font.size.1200': {
    '$value': '50px',
    '$extensions': {
      mode: {
        desktop: '50px',
        mobile: '62px',
      },
    },
  },
  'font.size.1300': {
    '$value': '60px',
    '$extensions': {
      mode: {
        desktop: '60px',
        mobile: '70px',
      },
    },
  },
};

export const modes = {
  'color.blue400': {
    lightest: '#378ef0',
    light: '#2680eb',
    dark: '#2680eb',
    darkest: '#1473e6',
  },
  'color.blue500': {
    lightest: '#2680eb',
    light: '#1473e6',
    dark: '#378ef0',
    darkest: '#2680eb',
  },
  'color.blue600': {
    lightest: '#1473e6',
    light: '#0d66d0',
    dark: '#4b9cf5',
    darkest: '#378ef0',
  },
  'color.blue700': {
    lightest: '#0d66d0',
    light: '#095aba',
    dark: '#5aa9fa',
    darkest: '#4b9cf5',
  },
  'color.gray50': {
    lightest: '#ffffff',
    light: '#ffffff',
    dark: '#252525',
    darkest: '#080808',
  },
  'color.gray75': {
    lightest: '#ffffff',
    light: '#fafafa',
    dark: '#2f2f2f',
    darkest: '#1a1a1a',
  },
  'color.gray100': {
    lightest: '#ffffff',
    light: '#f5f5f5',
    dark: '#323232',
    darkest: '#1e1e1e',
  },
  'color.gray200': {
    lightest: '#f4f4f4',
    light: '#eaeaea',
    dark: '#3e3e3e',
    darkest: '#2c2c2c',
  },
  'color.gray300': {
    lightest: '#eaeaea',
    light: '#e1e1e1',
    dark: '#4a4a4a',
    darkest: '#393939',
  },
  'color.gray400': {
    lightest: '#d3d3d3',
    light: '#cacaca',
    dark: '#5a5a5a',
    darkest: '#494949',
  },
  'color.gray500': {
    lightest: '#bcbcbc',
    light: '#b3b3b3',
    dark: '#6e6e6e',
    darkest: '#5c5c5c',
  },
  'color.gray600': {
    lightest: '#959595',
    light: '#8e8e8e',
    dark: '#909090',
    darkest: '#7c7c7c',
  },
  'color.gray700': {
    lightest: '#747474',
    light: '#6e6e6e',
    dark: '#b9b9b9',
    darkest: '#a2a2a2',
  },
  'color.gray800': {
    lightest: '#505050',
    light: '#4b4b4b',
    dark: '#e3e3e3',
    darkest: '#c8c8c8',
  },
  'color.gray900': {
    lightest: '#323232',
    light: '#2c2c2c',
    dark: '#ffffff',
    darkest: '#efefef',
  },
  'color.green400': {
    lightest: '#33ab84',
    light: '#2d9d78',
    dark: '#2d9d78',
    darkest: '#268e6c',
  },
  'color.green500': {
    lightest: '#2d9d78',
    light: '#268e6c',
    dark: '#33ab84',
    darkest: '#2d9d78',
  },
  'color.green600': {
    lightest: '#268e6c',
    light: '#12805c',
    dark: '#39b990',
    darkest: '#33ab84',
  },
  'color.green700': {
    lightest: '#12805c',
    light: '#107154',
    dark: '#3fc89c',
    darkest: '#39b990',
  },
  'color.red400': {
    lightest: '#ec5b62',
    light: '#e34850',
    dark: '#e34850',
    darkest: '#d7373f',
  },
  'color.red500': {
    lightest: '#e34850',
    light: '#d7373f',
    dark: '#ec5b62',
    darkest: '#e34850',
  },
  'color.red600': {
    lightest: '#d7373f',
    light: '#c9252d',
    dark: '#f76d74',
    darkest: '#ec5b62',
  },
  'color.red700': {
    lightest: '#c9252d',
    light: '#bb121a',
    dark: '#ff7b82',
    darkest: '#f76d74',
  },
  'color.orange400': {
    lightest: '#f29423',
    light: '#e68619',
    dark: '#e68619',
    darkest: '#da7b11',
  },
  'color.orange500': {
    lightest: '#e68619',
    light: '#da7b11',
    dark: '#f29423',
    darkest: '#e68619',
  },
  'color.orange600': {
    lightest: '#da7b11',
    light: '#cb6f10',
    dark: '#f9a43f',
    darkest: '#f29423',
  },
  'color.orange700': {
    lightest: '#cb6f10',
    light: '#bd640d',
    dark: '#ffb55b',
    darkest: '#f9a43f',
  },
  'color.label.celery400': {
    lightest: '#4bc35f',
    light: '#44b556',
    dark: '#44b556',
    darkest: '#3da74e',
  },
  'color.label.celery500': {
    lightest: '#44b556',
    light: '#3da74e',
    dark: '#4bc35f',
    darkest: '#44b556',
  },
  'color.label.celery600': {
    lightest: '#3da74e',
    light: '#3da74e',
    dark: '#51d267',
    darkest: '#4bc35f',
  },
  'color.label.celery700': {
    lightest: '#379947',
    light: '#3da74e',
    dark: '#58e06f',
    darkest: '#51d267',
  },
  'color.label.chartreuse400': {
    lightest: '#8ede49',
    light: '#85d044',
    dark: '#85d044',
    darkest: '#7cc33f',
  },
  'color.label.chartreuse500': {
    lightest: '#85d044',
    light: '#7cc33f',
    dark: '#8ede49',
    darkest: '#85d044',
  },
  'color.label.chartreuse600': {
    lightest: '#7cc33f',
    light: '#73b53a',
    dark: '#9bec54',
    darkest: '#8ede49',
  },
  'color.label.chartreuse700': {
    lightest: '#73b53a',
    light: '#6aa834',
    dark: '#a3f858',
    darkest: '#9bec54',
  },
  'color.label.fuchsia400': {
    lightest: '#cf3edc',
    light: '#c038cc',
    dark: '#c038cc',
    darkest: '#b130bd',
  },
  'color.label.fuchsia500': {
    lightest: '#c038cc',
    light: '#b130bd',
    dark: '#cf3edc',
    darkest: '#c038cc',
  },
  'color.label.fuchsia600': {
    lightest: '#b130bd',
    light: '#a228ad',
    dark: '#d951e5',
    darkest: '#cf3edc',
  },
  'color.label.fuchsia700': {
    lightest: '#a228ad',
    light: '#93219e',
    dark: '#e366ef',
    darkest: '#d951e5',
  },
  'color.label.indigo400': {
    lightest: '#7575f1',
    light: '#6767ec',
    dark: '#6767ec',
    darkest: '#5c5ce0',
  },
  'color.label.indigo500': {
    lightest: '#6767ec',
    light: '#5c5ce0',
    dark: '#7575f1',
    darkest: '#6767ec',
  },
  'color.label.indigo600': {
    lightest: '#5c5ce0',
    light: '#5151d3',
    dark: '#8282f6',
    darkest: '#7575f1',
  },
  'color.label.indigo700': {
    lightest: '#5151d3',
    light: '#4646c6',
    dark: '#9090fa',
    darkest: '#8282f6',
  },
  'color.label.magenta400': {
    lightest: '#e2499d',
    light: '#d83790',
    dark: '#d83790',
    darkest: '#ca2996',
  },
  'color.label.magenta500': {
    lightest: '#d83790',
    light: '#ce2783',
    dark: '#e2499d',
    darkest: '#d83790',
  },
  'color.label.magenta600': {
    lightest: '#ca2982',
    light: '#bc1c74',
    dark: '#ec5aaa',
    darkest: '#e2499d',
  },
  'color.label.magenta700': {
    lightest: '#bc1c74',
    light: '#ae0e66',
    dark: '#f56bb7',
    darkest: '#ec5aaa',
  },
  'color.label.purple400': {
    lightest: '#9d64e1',
    light: '#9256d9',
    dark: '#9256d9',
    darkest: '#864ccc',
  },
  'color.label.purple500': {
    lightest: '#9256d9',
    light: '#864ccc',
    dark: '#9d64e1',
    darkest: '#9256d9',
  },
  'color.label.purple600': {
    lightest: '#864ccc',
    light: '#7a42bf',
    dark: '#a873e9',
    darkest: '#9d64e1',
  },
  'color.label.purple700': {
    lightest: '#7a42bf',
    light: '#6f38b1',
    dark: '#b483f0',
    darkest: '#a873df',
  },
  'color.label.seafoam400': {
    lightest: '#20a3a8',
    light: '#1b959a',
    dark: '#1b959a',
    darkest: '#16878c',
  },
  'color.label.seafoam500': {
    lightest: '#1b959a',
    light: '#16878c',
    dark: '#20a3a8',
    darkest: '#1b959a',
  },
  'color.label.seafoam600': {
    lightest: '#16878c',
    light: '#0f797d',
    dark: '#23b2b8',
    darkest: '#20a3a8',
  },
  'color.label.seafoam700': {
    lightest: '#0f797d',
    light: '#096c6f',
    dark: '#26c0c7',
    darkest: '#23b2b8',
  },
  'color.label.yellow400': {
    lightest: '#edcc00',
    light: '#dfbf00',
    dark: '#dfbf00',
    darkest: '#d2b200',
  },
  'color.label.yellow500': {
    lightest: '#dfbf00',
    light: '#d2b200',
    dark: '#edcc00',
    darkest: '#dfbf00',
  },
  'color.label.yellow600': {
    lightest: '#d2b200',
    light: '#c4a600',
    dark: '#fad900',
    darkest: '#edcc00',
  },
  'color.label.yellow700': {
    lightest: '#c4a600',
    light: '#b79900',
    dark: '#ffe22e',
    darkest: '#fad900',
  },
  'font.size.50': {
    desktop: '11px',
    mobile: '13px',
  },
  'font.size.75': {
    desktop: '12px',
    mobile: '13px',
  },
  'font.size.100': {
    desktop: '14px',
    mobile: '17px',
  },
  'font.size.200': {
    desktop: '16px',
    mobile: '19px',
  },
  'font.size.300': {
    desktop: '18px',
    mobile: '22px',
  },
  'font.size.400': {
    desktop: '20px',
    mobile: '24px',
  },
  'font.size.500': {
    desktop: '22px',
    mobile: '27px',
  },
  'font.size.600': {
    desktop: '25px',
    mobile: '31px',
  },
  'font.size.700': {
    desktop: '28px',
    mobile: '34px',
  },
  'font.size.800': {
    desktop: '32px',
    mobile: '39px',
  },
  'font.size.900': {
    desktop: '36px',
    mobile: '44px',
  },
  'font.size.1000': {
    desktop: '40px',
    mobile: '49px',
  },
  'font.size.1100': {
    desktop: '45px',
    mobile: '55px',
  },
  'font.size.1200': {
    desktop: '50px',
    mobile: '62px',
  },
  'font.size.1300': {
    desktop: '60px',
    mobile: '70px',
  },
};

/** Get individual token */
export function token(tokenID, modeName) {
  if (modeName && modes[tokenID] && modeName in modes[tokenID]) return modes[tokenID][modeName];
  return tokens[tokenID];
}
