/** ------------------------------------------
 *  Autogenerated by ⛋ Terrazzo. DO NOT EDIT!
 * ------------------------------------------- */

import type { Resolver, TokenNormalizedSet } from "@terrazzo/parser";

export const PERMUTATIONS: Record<string, TokenNormalizedSet>;

type InputType = {
  "theme": "light" | "dark";
  "size": "desktop" | "mobile";
};;

/** Produce a token set from a given input. */
export const resolver: Pick<Resolver<InputType>, "apply" | "listPermutations">;
