/** ------------------------------------------
 *  Autogenerated by ⛋ Terrazzo. DO NOT EDIT!
 * ------------------------------------------- */

import type {
  ColorTokenNormalized,
  DimensionTokenNormalized,
  FontFamilyTokenNormalized,
} from "@terrazzo/parser";

export declare const tokens: {
  "color.black": Record<".", ColorTokenNormalized["$value"]>;
  "color.blue": Record<".", ColorTokenNormalized["$value"]>;
  "color.blueDark": Record<".", ColorTokenNormalized["$value"]>;
  "color.blueDarker": Record<".", ColorTokenNormalized["$value"]>;
  "color.blueLight": Record<".", ColorTokenNormalized["$value"]>;
  "color.blueLighter": Record<".", ColorTokenNormalized["$value"]>;
  "color.blueText": Record<".", ColorTokenNormalized["$value"]>;
  "color.green": Record<".", ColorTokenNormalized["$value"]>;
  "color.greenDark": Record<".", ColorTokenNormalized["$value"]>;
  "color.greenDarker": Record<".", ColorTokenNormalized["$value"]>;
  "color.greenLight": Record<".", ColorTokenNormalized["$value"]>;
  "color.greenLighter": Record<".", ColorTokenNormalized["$value"]>;
  "color.greenText": Record<".", ColorTokenNormalized["$value"]>;
  "color.indigo": Record<".", ColorTokenNormalized["$value"]>;
  "color.indigoDark": Record<".", ColorTokenNormalized["$value"]>;
  "color.indigoDarker": Record<".", ColorTokenNormalized["$value"]>;
  "color.indigoLight": Record<".", ColorTokenNormalized["$value"]>;
  "color.indigoLighter": Record<".", ColorTokenNormalized["$value"]>;
  "color.indigoText": Record<".", ColorTokenNormalized["$value"]>;
  "color.ink": Record<".", ColorTokenNormalized["$value"]>;
  "color.inkLight": Record<".", ColorTokenNormalized["$value"]>;
  "color.inkLighter": Record<".", ColorTokenNormalized["$value"]>;
  "color.inkLightest": Record<".", ColorTokenNormalized["$value"]>;
  "color.orange": Record<".", ColorTokenNormalized["$value"]>;
  "color.orangeDark": Record<".", ColorTokenNormalized["$value"]>;
  "color.orangeDarker": Record<".", ColorTokenNormalized["$value"]>;
  "color.orangeLight": Record<".", ColorTokenNormalized["$value"]>;
  "color.orangeLighter": Record<".", ColorTokenNormalized["$value"]>;
  "color.orangeText": Record<".", ColorTokenNormalized["$value"]>;
  "color.purple": Record<".", ColorTokenNormalized["$value"]>;
  "color.purpleDark": Record<".", ColorTokenNormalized["$value"]>;
  "color.purpleDarker": Record<".", ColorTokenNormalized["$value"]>;
  "color.purpleLight": Record<".", ColorTokenNormalized["$value"]>;
  "color.purpleLighter": Record<".", ColorTokenNormalized["$value"]>;
  "color.purpleText": Record<".", ColorTokenNormalized["$value"]>;
  "color.red": Record<".", ColorTokenNormalized["$value"]>;
  "color.redDark": Record<".", ColorTokenNormalized["$value"]>;
  "color.redDarker": Record<".", ColorTokenNormalized["$value"]>;
  "color.redLight": Record<".", ColorTokenNormalized["$value"]>;
  "color.redLighter": Record<".", ColorTokenNormalized["$value"]>;
  "color.redText": Record<".", ColorTokenNormalized["$value"]>;
  "color.sky": Record<".", ColorTokenNormalized["$value"]>;
  "color.skyDark": Record<".", ColorTokenNormalized["$value"]>;
  "color.skyLight": Record<".", ColorTokenNormalized["$value"]>;
  "color.skyLighter": Record<".", ColorTokenNormalized["$value"]>;
  "color.teal": Record<".", ColorTokenNormalized["$value"]>;
  "color.tealDark": Record<".", ColorTokenNormalized["$value"]>;
  "color.tealDarker": Record<".", ColorTokenNormalized["$value"]>;
  "color.tealLight": Record<".", ColorTokenNormalized["$value"]>;
  "color.tealLighter": Record<".", ColorTokenNormalized["$value"]>;
  "color.tealText": Record<".", ColorTokenNormalized["$value"]>;
  "color.white": Record<".", ColorTokenNormalized["$value"]>;
  "color.yellow": Record<".", ColorTokenNormalized["$value"]>;
  "color.yellowDark": Record<".", ColorTokenNormalized["$value"]>;
  "color.yellowDarker": Record<".", ColorTokenNormalized["$value"]>;
  "color.yellowLight": Record<".", ColorTokenNormalized["$value"]>;
  "color.yellowLighter": Record<".", ColorTokenNormalized["$value"]>;
  "color.yellowText": Record<".", ColorTokenNormalized["$value"]>;
  "font.family.base": Record<".", FontFamilyTokenNormalized["$value"]>;
  "font.family.mono": Record<".", FontFamilyTokenNormalized["$value"]>;
  "space.base": Record<".", DimensionTokenNormalized["$value"]>;
  "space.baseTight": Record<".", DimensionTokenNormalized["$value"]>;
  "space.extraLoose": Record<".", DimensionTokenNormalized["$value"]>;
  "space.extraTight": Record<".", DimensionTokenNormalized["$value"]>;
  "space.loose": Record<".", DimensionTokenNormalized["$value"]>;
  "space.none": Record<".", DimensionTokenNormalized["$value"]>;
  "space.tight": Record<".", DimensionTokenNormalized["$value"]>;
};

export declare function token<K extends keyof typeof tokens>(tokenID: K, modeName?: never): (typeof tokens)[K]["."];
export declare function token<K extends keyof typeof tokens, M extends keyof (typeof tokens)[K]>(tokenID: K, modeName: M): (typeof tokens)[K][M];
