/** ------------------------------------------
 *  Autogenerated by ⛋ Terrazzo. DO NOT EDIT!
 * ------------------------------------------- */

export const tokens = {
  "color.black": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0,
        0
      ],
      "alpha": 1,
      "hex": "#000000"
    },
  },
  "color.blue": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0.43529411764705883,
        0.7333333333333333
      ],
      "alpha": 1,
      "hex": "#006fbb"
    },
  },
  "color.blueDark": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.03137254901960784,
        0.3058823529411765,
        0.5411764705882353
      ],
      "alpha": 1,
      "hex": "#084e8a"
    },
  },
  "color.blueDarker": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0.0784313725490196,
        0.1607843137254902
      ],
      "alpha": 1,
      "hex": "#001429"
    },
  },
  "color.blueLight": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.7058823529411765,
        0.8823529411764706,
        0.9803921568627451
      ],
      "alpha": 1,
      "hex": "#b4e1fa"
    },
  },
  "color.blueLighter": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.9215686274509803,
        0.9607843137254902,
        0.9803921568627451
      ],
      "alpha": 1,
      "hex": "#ebf5fa"
    },
  },
  "color.blueText": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.24313725490196078,
        0.3058823529411765,
        0.3411764705882353
      ],
      "alpha": 1,
      "hex": "#3e4e57"
    },
  },
  "color.green": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.3137254901960784,
        0.7215686274509804,
        0.23529411764705882
      ],
      "alpha": 1,
      "hex": "#50b83c"
    },
  },
  "color.greenDark": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.06274509803921569,
        0.5019607843137255,
        0.2627450980392157
      ],
      "alpha": 1,
      "hex": "#108043"
    },
  },
  "color.greenDarker": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.09019607843137255,
        0.21176470588235294,
        0.18823529411764706
      ],
      "alpha": 1,
      "hex": "#173630"
    },
  },
  "color.greenLight": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.7333333333333333,
        0.8980392156862745,
        0.7019607843137254
      ],
      "alpha": 1,
      "hex": "#bbe5b3"
    },
  },
  "color.greenLighter": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.8901960784313725,
        0.9450980392156862,
        0.8745098039215686
      ],
      "alpha": 1,
      "hex": "#e3f1df"
    },
  },
  "color.greenText": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.2549019607843137,
        0.30980392156862746,
        0.24313725490196078
      ],
      "alpha": 1,
      "hex": "#414f3e"
    },
  },
  "color.indigo": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.3607843137254902,
        0.41568627450980394,
        0.7686274509803922
      ],
      "alpha": 1,
      "hex": "#5c6ac4"
    },
  },
  "color.indigoDark": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.12549019607843137,
        0.1803921568627451,
        0.47058823529411764
      ],
      "alpha": 1,
      "hex": "#202e78"
    },
  },
  "color.indigoDarker": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0.023529411764705882,
        0.2235294117647059
      ],
      "alpha": 1,
      "hex": "#000639"
    },
  },
  "color.indigoLight": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.7019607843137254,
        0.7372549019607844,
        0.9607843137254902
      ],
      "alpha": 1,
      "hex": "#b3bcf5"
    },
  },
  "color.indigoLighter": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.9568627450980393,
        0.9607843137254902,
        0.9803921568627451
      ],
      "alpha": 1,
      "hex": "#f4f5fa"
    },
  },
  "color.indigoText": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.24313725490196078,
        0.2549019607843137,
        0.3333333333333333
      ],
      "alpha": 1,
      "hex": "#3e4155"
    },
  },
  "color.ink": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.12941176470588237,
        0.16862745098039217,
        0.21176470588235294
      ],
      "alpha": 1,
      "hex": "#212b36"
    },
  },
  "color.inkLight": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.27058823529411763,
        0.30980392156862746,
        0.3568627450980392
      ],
      "alpha": 1,
      "hex": "#454f5b"
    },
  },
  "color.inkLighter": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.38823529411764707,
        0.45098039215686275,
        0.5058823529411764
      ],
      "alpha": 1,
      "hex": "#637381"
    },
  },
  "color.inkLightest": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.5686274509803921,
        0.6196078431372549,
        0.6705882352941176
      ],
      "alpha": 1,
      "hex": "#919eab"
    },
  },
  "color.orange": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.9568627450980393,
        0.5764705882352941,
        0.25882352941176473
      ],
      "alpha": 1,
      "hex": "#f49342"
    },
  },
  "color.orangeDark": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.7529411764705882,
        0.3411764705882353,
        0.09019607843137255
      ],
      "alpha": 1,
      "hex": "#c05717"
    },
  },
  "color.orangeDarker": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.2901960784313726,
        0.08235294117647059,
        0.01568627450980392
      ],
      "alpha": 1,
      "hex": "#4a1504"
    },
  },
  "color.orangeLight": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        1,
        0.7725490196078432,
        0.5450980392156862
      ],
      "alpha": 1,
      "hex": "#ffc58b"
    },
  },
  "color.orangeLighter": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.9882352941176471,
        0.9215686274509803,
        0.8588235294117647
      ],
      "alpha": 1,
      "hex": "#fcebdb"
    },
  },
  "color.orangeText": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.34901960784313724,
        0.26666666666666666,
        0.18823529411764706
      ],
      "alpha": 1,
      "hex": "#594430"
    },
  },
  "color.purple": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.611764705882353,
        0.41568627450980394,
        0.8705882352941177
      ],
      "alpha": 1,
      "hex": "#9c6ade"
    },
  },
  "color.purpleDark": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.3137254901960784,
        0.1411764705882353,
        0.5607843137254902
      ],
      "alpha": 1,
      "hex": "#50248f"
    },
  },
  "color.purpleDarker": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.13725490196078433,
        0,
        0.3176470588235294
      ],
      "alpha": 1,
      "hex": "#230051"
    },
  },
  "color.purpleLight": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.8901960784313725,
        0.8156862745098039,
        1
      ],
      "alpha": 1,
      "hex": "#e3d0ff"
    },
  },
  "color.purpleLighter": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.9647058823529412,
        0.9411764705882353,
        0.9921568627450981
      ],
      "alpha": 1,
      "hex": "#f6f0fd"
    },
  },
  "color.purpleText": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.3137254901960784,
        0.28627450980392155,
        0.35294117647058826
      ],
      "alpha": 1,
      "hex": "#50495a"
    },
  },
  "color.red": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.8705882352941177,
        0.21176470588235294,
        0.09411764705882353
      ],
      "alpha": 1,
      "hex": "#de3618"
    },
  },
  "color.redDark": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.7490196078431373,
        0.027450980392156862,
        0.06666666666666667
      ],
      "alpha": 1,
      "hex": "#bf0711"
    },
  },
  "color.redDarker": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.2,
        0.00392156862745098,
        0.00392156862745098
      ],
      "alpha": 1,
      "hex": "#330101"
    },
  },
  "color.redLight": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.996078431372549,
        0.6784313725490196,
        0.6039215686274509
      ],
      "alpha": 1,
      "hex": "#fead9a"
    },
  },
  "color.redLighter": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.984313725490196,
        0.9176470588235294,
        0.8980392156862745
      ],
      "alpha": 1,
      "hex": "#fbeae5"
    },
  },
  "color.redText": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.34509803921568627,
        0.23529411764705882,
        0.20784313725490197
      ],
      "alpha": 1,
      "hex": "#583c35"
    },
  },
  "color.sky": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.8745098039215686,
        0.8901960784313725,
        0.9098039215686274
      ],
      "alpha": 1,
      "hex": "#dfe3e8"
    },
  },
  "color.skyDark": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.7686274509803922,
        0.803921568627451,
        0.8352941176470589
      ],
      "alpha": 1,
      "hex": "#c4cdd5"
    },
  },
  "color.skyLight": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.9568627450980393,
        0.9647058823529412,
        0.9725490196078431
      ],
      "alpha": 1,
      "hex": "#f4f6f8"
    },
  },
  "color.skyLighter": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.9764705882352941,
        0.9803921568627451,
        0.984313725490196
      ],
      "alpha": 1,
      "hex": "#f9fafb"
    },
  },
  "color.teal": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.2784313725490196,
        0.7568627450980392,
        0.7490196078431373
      ],
      "alpha": 1,
      "hex": "#47c1bf"
    },
  },
  "color.tealDark": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0.5176470588235295,
        0.5568627450980392
      ],
      "alpha": 1,
      "hex": "#00848e"
    },
  },
  "color.tealDarker": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0,
        0.19215686274509805,
        0.20784313725490197
      ],
      "alpha": 1,
      "hex": "#003135"
    },
  },
  "color.tealLight": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.7176470588235294,
        0.9254901960784314,
        0.9254901960784314
      ],
      "alpha": 1,
      "hex": "#b7ecec"
    },
  },
  "color.tealLighter": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.8784313725490196,
        0.9607843137254902,
        0.9607843137254902
      ],
      "alpha": 1,
      "hex": "#e0f5f5"
    },
  },
  "color.tealText": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.25098039215686274,
        0.3254901960784314,
        0.3215686274509804
      ],
      "alpha": 1,
      "hex": "#405352"
    },
  },
  "color.white": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        1,
        1,
        1
      ],
      "alpha": 1,
      "hex": "#ffffff"
    },
  },
  "color.yellow": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.9333333333333333,
        0.7607843137254902,
        0
      ],
      "alpha": 1,
      "hex": "#eec200"
    },
  },
  "color.yellowDark": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.5411764705882353,
        0.3803921568627451,
        0.08627450980392157
      ],
      "alpha": 1,
      "hex": "#8a6116"
    },
  },
  "color.yellowDarker": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.3411764705882353,
        0.23137254901960785,
        0
      ],
      "alpha": 1,
      "hex": "#573b00"
    },
  },
  "color.yellowLight": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        1,
        0.9176470588235294,
        0.5411764705882353
      ],
      "alpha": 1,
      "hex": "#ffea8a"
    },
  },
  "color.yellowLighter": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.9882352941176471,
        0.9450980392156862,
        0.803921568627451
      ],
      "alpha": 1,
      "hex": "#fcf1cd"
    },
  },
  "color.yellowText": {
    ".": {
      "colorSpace": "srgb",
      "components": [
        0.34901960784313724,
        0.3176470588235294,
        0.18823529411764706
      ],
      "alpha": 1,
      "hex": "#595130"
    },
  },
  "font.family.base": {
    ".": [
      "-apple-system",
      "BlinkMacSystemFont",
      "San Francisco",
      "Segoe UI",
      "Roboto",
      "Helvetica Neue",
      "sans-serif"
    ],
  },
  "font.family.mono": {
    ".": [
      "Monaco",
      "Consolas",
      "Lucida Console",
      "monospace"
    ],
  },
  "space.base": {
    ".": {
      "value": 16,
      "unit": "px"
    },
  },
  "space.baseTight": {
    ".": {
      "value": 12,
      "unit": "px"
    },
  },
  "space.extraLoose": {
    ".": {
      "value": 32,
      "unit": "px"
    },
  },
  "space.extraTight": {
    ".": {
      "value": 4,
      "unit": "px"
    },
  },
  "space.loose": {
    ".": {
      "value": 20,
      "unit": "px"
    },
  },
  "space.none": {
    ".": {
      "value": 0,
      "unit": "px"
    },
  },
  "space.tight": {
    ".": {
      "value": 8,
      "unit": "px"
    },
  },
};

/** Get individual token */
export function token(tokenID, modeName = ".") {
  return tokens[tokenID]?.[modeName];
}
